### ISSUE TITLE
We need to migrate teh help system from GeoSight

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#1014]
CC @amyburness 

Can we please implement the same help system we use in GeoSight.

Task it to @meomancer since he knows how it works

@meomancer do it by making a pip module for the backend and an npm module for the front end.

**Comment by amyburness** [comment]
@MarinaKartoza I need some time scheduled to @meomancer to implement this. 

@meomancer can you estimate how long this ticket will take?

**Comment by meomancer** [comment]
hi @amyburness @timlinux 
There are 2 things that i need to work on
- [ ] Backend as python library (using pip module)
- [ ] Frontend as react library (using npm module)

For me per task would be 2 days
- Split the code and make it as library (4 hours)
- Make it ready to be installed as standalone (8 hours, include RnD)
- Doing test and clean up (4 hours)

So i would says around 32 hours in total.
