### ISSUE TITLE
UI issue with Species filter

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1021]
![image](https://github.com/kartoza/sawps/assets/90245715/038c3f5d-9569-4ce4-a272-b5ebd671ecc1)
1. One species is selected at a time. Therefore, remove checkboxes and badge.
2. Allow searching
3. The species should be ordered in alphabetical order

An example of an interface:
![image](https://github.com/kartoza/sawps/assets/90245715/f3138bb8-1ec7-45e7-b500-bdea824ccdb8)
The user opens dropdown, the values are ordered alphabetically, the user can input the first few letters and the viable options are shown when I select my option, it collapses and shows my selected option
![image](https://github.com/kartoza/sawps/assets/90245715/54cf29e8-df10-4d03-8963-81078a55e57f)

**Comment by amyburness** [comment]
@ketankartoza I know you are finalizing the filters soon please incorporate this feedback from Tim. 
make the species dropdown a searchable alphabetical list.
