### ISSUE TITLE
Inconsistent icon effects

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1022]
None of the icons have a shadow effect on them so please drop the shadow effect
![image](https://github.com/kartoza/sawps/assets/90245715/cada2c25-cb4f-450e-a742-e224ed2ced2e)

**Comment by amyburness** [comment]
Yes no drop shadow and there is also a problem with the (i) and the elephant they are stretched strangely. If I supply the correct SVG for them can they be replaced throughout?
@tinashechiraya @ketankartoza

**Comment by ketankartoza** [comment]
@amyburness please send I will replace this icons.
