### ISSUE TITLE
What is the point of this dropdown?

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1024]
![image](https://github.com/kartoza/sawps/assets/90245715/d2898015-dc67-4639-acdc-d65b692f48f4)

**Comment by LunaAsefaw** [comment]
Please avoid shortening the words, please right out the full word

**Comment by amyburness** [comment]
@tinashechiraya the standard is "Two-factor authentication" Please use it throughout. 

@timlinux @LunaAsefaw The drop-down would eventually contain different options like an authenticator app or Yubi key. should @tinashechiraya add the Yubi option now or just remove the dropdown entirely?
