### ISSUE TITLE
Pivot or float the download buttons so they're unaffected by the scrolls

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1025]
The data and  metrics tab have could have lots of records/graphs so to avoid forcing the user to scroll to the end, please pivot these buttons or make it float
![image](https://github.com/kartoza/sawps/assets/90245715/e29bf16b-5224-431b-8a17-a7bae7f55344)
Currently the button on the metrics tab is cut off
![image](https://github.com/kartoza/sawps/assets/90245715/d1bc4786-63c3-412a-a97a-210209666515)

**Comment by amyburness** [comment]
@tinashechiraya @ketankartoza Please implement this logic throughout the UI on all your pages.

**Comment by LunaAsefaw** [comment]
This is not implemented on the report tab, I have to scroll down to access the download buttons @Fanevanjanahary @tinashechiraya @ketankartoza 
![image](https://github.com/kartoza/sawps/assets/90245715/754c582b-f43e-4224-914a-0557596bcd0f)

**Comment by Fanevanjanahary** [comment]
@LunaAsefaw the download data PR is not merged yet
