### ISSUE TITLE
Change alignment of graph heading for area graph

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1048]
![image](https://github.com/kartoza/sawps/assets/90245715/711e784c-316a-4585-8fdf-a92191ae3bcb)
all the other graphs have a central heading besides the area graph

**Comment by LunaAsefaw** [comment]
@zamuzakki 

![Image](https://github.com/kartoza/sawps/assets/90245715/6049ec00-5db5-43de-8c41-0d1da41bc89f)

**Comment by zamuzakki** [comment]
The graph headings alignment are now consistent.
![Screen Shot 2023-11-06 at 12 57 15-fullpage](https://github.com/kartoza/sawps/assets/7352963/0f28162f-968f-484d-8f0f-99a0fcaf86d1)
