### ISSUE TITLE
Different UI for population certainity online form

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1051]
Using the description field to select the level of certainty is fine if we have three levels (good, bad, medium) etc but the current range is from 1-10, which makes this difficult.
![image](https://github.com/kartoza/sawps/assets/90245715/93416fce-3f40-4281-a285-e81f9f047de7)
Can we have something like this instead? Except it ranges from 1-10.
![image](https://github.com/kartoza/sawps/assets/90245715/d8c4d877-6ccc-4f8d-aa5b-2efb0e115307)

**Comment by tinashechiraya** [comment]
@LunaAsefaw so in that population estimate certainty instead of those options, it should just give you that ratings with option 1- 10 ?

**Comment by LunaAsefaw** [comment]
yes, then please indicate at 1 that 'Least confident' and by 10 'Most confident'

**Comment by tinashechiraya** [comment]
https://github.com/kartoza/sawps/pull/1104
