### ISSUE TITLE
make profile pages responsive 

### ISSUE THREAD

**Issue by tinashechiraya** [kartoza/sawps#1065]
on smaller screens the tables are not fitting so they need a horizontal scroll added to them

also the footer is in the wrong position

**Comment by tinashechiraya** [comment]
> The profile tab supports mobile screens but the other tabs do not and organisation does not show
> 
>  Mobile_view.mp4

@LunaAsefaw there's a horizontal scroll to see the other tabs like organisation ...remember on mobile phones its touch screen so they can simply swipe and it scrolls to the other tabs

**Comment by LunaAsefaw** [comment]
@tinashechiraya oh, I see, that makes sense. So far, the only ones that are not clear on a phone are the charts on the landing page (I have made a ticket for this and assigned it to Danang) then on the charts tab, I saw a slight overlap between the legend and title but the rest seem to work on my screen
![image](https://github.com/kartoza/sawps/assets/90245715/a15e4022-a29d-4066-9765-b460b2111fdf)
