### ISSUE TITLE
Map interactions

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#1132]
## Data scientist and admin

![image](https://github.com/kartoza/sawps/assets/178003/5a40c168-f545-46bc-a933-d857939adb63)

Flip map to 3d to see extruded values (counts per property)

![image](https://github.com/kartoza/sawps/assets/178003/b67fd726-7316-4830-9359-c3c446534c2c)

# Decision maker

- No org option
- No property option
- Selecting species will extrude the counts per province compliant with the other filters

![image](https://github.com/kartoza/sawps/assets/178003/a8d2ae56-362c-4572-aa70-260875e381d1)

**Comment by danangmassandy** [comment]
Related with #1318

**Comment by danangmassandy** [comment]
Preview:
![Screenshot_4751](https://github.com/kartoza/sawps/assets/5819076/0da54c49-62ff-4f45-ab83-2f1d54950706)

![Screenshot_4752](https://github.com/kartoza/sawps/assets/5819076/09eae07a-a752-4c6b-afda-f4df786f57b1)
