### ISSUE TITLE
Chart UI Updates

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#1147]
Please see the screenshot below
![image](https://github.com/kartoza/sawps/assets/77841514/6304e99a-6a0b-428e-a04f-a4523b1b6996)
![image](https://github.com/kartoza/sawps/assets/77841514/0dcf00c5-962c-423a-a615-7bd50d261700)

**Comment by tinashechiraya** [comment]
create charts container
this should get rid of the shadows
this should achieve responsiveness
this should evenly distribute the charts
this should define the rules of 2 charts per row
this should define the spacing between the charts 
this should ensure the charts fit on the page without the horizontal scroll

**Comment by LunaAsefaw** [comment]
![image](https://github.com/kartoza/sawps/assets/90245715/2f81e48b-0dc7-499f-9d13-1f06f7fed0ea)
