### ISSUE TITLE
Where are the activity tables in the reports tab?

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#1148]
I can't see the activity tables in the reports tab
![image](https://github.com/kartoza/sawps/assets/77841514/04c16e83-f7c4-43da-a567-00cab15876bc)

**Comment by amyburness** [comment]
not the logic when i select each activity I want to see a full table of that activity. and the rest of the filters must work on these tables.

**Comment by ketankartoza** [comment]
> not the logic when i select each activity I want to see a full table of that activity. and the rest of the filters must work on these tables.

@amyburness Only the Organisation member and manager can see activity data in this format another user role will only be able to see the aggregate data of the activity in the activity table.

**Comment by amyburness** [comment]
@ketankartoza 

Data contributors (both) - can see the activity tables for their properties. 
Data consumers (both) - can see the aggregated activity for their province or nationally
Data scientists and administrators/superusers - can see the activity data for all the organizations and properties. 

This logic is consistent for all the report types please apply to all the tables
