### ISSUE TITLE
Ensure table fills vertical space

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#1167]
![image](https://github.com/kartoza/sawps/assets/178003/90ef7dd1-0ceb-41f9-8600-ba6564a19e92)

**Comment by zamuzakki** [comment]
Now that we have report topper, the table fills vertical space. 
![aa](https://github.com/kartoza/sawps/assets/7352963/64724805-1903-4865-a51b-aaa5edfc0b75)
![Screenshot from 2023-11-06 14-03-11](https://github.com/kartoza/sawps/assets/7352963/908c228a-8647-4068-bed6-46ff462ba71d)
![Screenshot from 2023-11-06 14-02-50](https://github.com/kartoza/sawps/assets/7352963/b775b695-9874-4ee5-bd73-a3b26135cc25)
