### ISSUE TITLE
R Graph 1: Population trends by subpopulation

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1168]
![Image](https://github.com/kartoza/sawps/assets/90245715/ff0a839b-31b0-49b7-a82a-d8dc3048a5e0)

**Comment by danangmassandy** [comment]
@LunaAsefaw @amyburness this trend chart that is for each property, are we going to show all the charts in the trend page? I think current behavior of the filter is to select every properties. So, I wonder what is the best layout to show charts for many properties.
