### ISSUE TITLE
Refactor data_table and report

### ISSUE THREAD

**Issue by dimasciput** [kartoza/sawps#1241]
Enhance the efficiency and maintainability of the data_table : 
- [x] Use Serializer for Data Returns
- [x] Reduce Code Redundancy
- [x] Update frontend components to parse and render the newly serialized data outputs correctly

**Comment by zamuzakki** [comment]
I've made PR for this ticket, addressing the 3 tasks.

**Comment by LunaAsefaw** [comment]
@dimasciput do you pass this ticket?
