### ISSUE TITLE
Documentation: Report filter

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1296]
Documentation on the different report filters and what each filter shows

**Comment by ketankartoza** [comment]
@LunaAsefaw by different report filters you mean all the filters of report type? or all the filters available in the filter panel?
Please confirm.

**Comment by LunaAsefaw** [comment]
@ketankartoza just focussing on the report type. So please show that we have specific report types and what each ones shows so property shows property information such as property area, species found on the property etc then species shows the count for that year etc. I just saw that we now have a province filter in the report tab, that will be for national data scientists and consumers so discuss that too
