### ISSUE TITLE
update to the reports tables and page

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#1312]
- [x] make the column widths dynamic (calculate the width of the table and then make the number of columns fit across the frame.
- [x] make the scientific name and common name columns from all tables not visible by default as they are covered in the report header (however they must be shown in the downloaded version of the report table.)
- [x] Also by default make the scientific name and common name options in the  filer columns dropdown menu unselected 
- [x] add a column after the property name called Property short code that shows the property shortcode 
- [x] add a column after the organisation name called Organisation short code that shows the organization shortcode

**Comment by zamuzakki** [comment]
> however they must be shown in the downloaded version of the report table.

@Fanevanjanahary could you handle the downloaded report table version? It is part of the CSV/Excel export isn't it @amyburness ?

**Comment by amyburness** [comment]
Hey @zamuzakki 
It should be the scientific name 

@tinashechiraya how are the short codes generated and stored?

**Comment by zamuzakki** [comment]
@amyburness Sorry, I meant "It currently only contain scientific name".

**Comment by zamuzakki** [comment]
Updating the size to cater short code generation features.
