### ISSUE TITLE
update the chart on the map panel

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#1315]
the charts on the map panel need to work and show the appropriate data. 
![image](https://github.com/kartoza/sawps/assets/77841514/6dddf967-41b3-4e41-a38a-5651bbbebcc0)

**Comment by LunaAsefaw** [comment]
The images below show that planned hunt/cull is not shown on the graph and only one record for euthanasia is shown (the lastest record only)

![Image](https://github.com/kartoza/sawps/assets/90245715/b46c0597-90e9-467f-bddf-30c1299ddfd2)



![Image](https://github.com/kartoza/sawps/assets/90245715/d4a8c7a5-ae48-4bbb-b484-717587e1b87c)



![Image](https://github.com/kartoza/sawps/assets/90245715/83775441-1f8f-47ce-a5f4-4d2f8c1cf91c)

**Comment by LunaAsefaw** [comment]
@amyburness does the activity chart show the latest year or the sum. For example, in the screenshot above from Danang, the planned hunt is 29 when both years are added. Do we only show the last year's data or do we show the trend (like the line graph for the years) but perhaps stacked to show the different years (stacked to show the total overtime though)?
