### ISSUE TITLE
Finalise the charts download page

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#1316]
The charts download page should have all the current filtered charts on it and be topped by the report topper. 
speak to @zamuzakki about the topper

**Comment by zamuzakki** [comment]
@amyburness Topper is now added to charts PDF.
Sample process and file: https://github.com/kartoza/sawps/pull/1516

**Comment by LunaAsefaw** [comment]
@amyburness @dimasciput is it okay if the chart is across two pages? I am not sure if something can be done about that
