### ISSUE TITLE
Add 3D functionality to the Map

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#1318]
the polygons and points (as a pillar) should extrude from the map based on the species count values.

**Comment by danangmassandy** [comment]
For now, I will give this ticket size of 8 for RnD (probably check with Irwan that has implemented in other project). Once I know more detail about the  implementation, I will update the size of this ticket.

**Comment by danangmassandy** [comment]
TODO:

- [ ] Counts per province for Decision Maker
- [ ] Counts per property for Data scientist + Admin

**Comment by danangmassandy** [comment]
Preview:
![Screenshot_4751](https://github.com/kartoza/sawps/assets/5819076/0da54c49-62ff-4f45-ab83-2f1d54950706)

![Screenshot_4752](https://github.com/kartoza/sawps/assets/5819076/09eae07a-a752-4c6b-afda-f4df786f57b1)

**Comment by LunaAsefaw** [comment]
Worked for me too
![image](https://github.com/kartoza/sawps/assets/90245715/bea389ea-27ee-499a-81b0-2f6bd686ace9)
