### ISSUE TITLE
Difference in uploaded shapefile and selected parcels

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1324]
This is the area digitised on the map
![image](https://github.com/kartoza/sawps/assets/90245715/9a495e05-8067-4df2-b9ba-0e912a1562a9)
but this was the shape provided
![image](https://github.com/kartoza/sawps/assets/90245715/91becc7d-d2fe-4d29-893a-b7236c49253e)

**Comment by LunaAsefaw** [comment]
The pictures above is for Reitfontein and the ones below are for Mziki
![image](https://github.com/kartoza/sawps/assets/90245715/5594068c-8e71-434e-8633-c03f25cdbaac)
![image](https://github.com/kartoza/sawps/assets/90245715/17399f8f-1a77-4da4-a948-30cd704299c0)

**Comment by danangmassandy** [comment]
As discussed, I will implement approach similar to QGIS plugin (https://github.com/HeikkiVesanto/SelectWithin).

- Search parcels by bbox query
- Calculate parcels centroid
- Do Centroid based selection

**Comment by danangmassandy** [comment]
@LunaAsefaw can I have your shapefile for testing? My test case will select the parcels from your shapefile and ensure that the neighbor parcels are not selected. Thanks,
