### ISSUE TITLE
Tab should just say 'SAWPS'

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#1337]
![image](https://github.com/kartoza/sawps/assets/178003/8752f55f-2aff-40e6-8c0e-dfed9604d10d)

**Comment by LunaAsefaw** [comment]
@ketankartoza the other pages still say other things (page name) instead of just saying SAWPS 

![Image](https://github.com/kartoza/sawps/assets/90245715/269c2f85-64a2-40ec-b2dd-e31aa6c1f8da)

**Comment by dimasciput** [comment]
@LunaAsefaw @timlinux I think displaying only "SAWPS" does not effectively indicate the current page. Perhaps something like "SAWPS - Profile" would be better.
