### ISSUE TITLE
Filtering columns

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1338]
When one report is selected, the correct columns are displayed to be filtered out but when multiple reports are selected, the only filter columns that work are the columns that are shown on the property report so you cannot filter out columns that exist on the other reports
![image](https://github.com/kartoza/sawps/assets/90245715/1f91847b-e7d5-49fa-9d54-2a0d4bb43cc0)

**Comment by LunaAsefaw** [comment]
@zamuzakki the filter function works for all the reports (even when they are all selected) but nothing works for Activity.

**Comment by zamuzakki** [comment]
@LunaAsefaw I seems to be working.
All reports
[Uploading Kazam_screencast_00037.webm…]()

Activity report
[Kazam_screencast_00038.webm](https://github.com/kartoza/sawps/assets/7352963/62c66d57-daba-451a-8d02-03de8ea48711)

**Comment by zamuzakki** [comment]
@LunaAsefaw  Now filtering columns will also work when only Activity Report is shown.
https://github.com/kartoza/sawps/pull/1518
