### ISSUE TITLE
Species icon in header do not correspond with selected species

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1343]
![image](https://github.com/kartoza/sawps/assets/90245715/1d96ddfc-dee8-49f7-a0e3-72fa21f048de)
For species that do not have an icon, please use a generic icon.

**Comment by LunaAsefaw** [comment]
@amyburness do we have a generic icon for other species?

**Comment by LunaAsefaw** [comment]
@zamuzakki tbehe generic icon is currently used on all
![image](https://github.com/kartoza/sawps/assets/90245715/b515e193-c978-4fa5-b45e-bfb15402953b)

**Comment by zamuzakki** [comment]
@LunaAsefaw You need to generate topper icon by uploading SVG file to the graph icon.
I've uploaded  graph icon to https://sawps.sta.do.kartoza.com/admin/species/taxon/14/, which will also automatically generate topper icon and icon for front page. 
![image](https://github.com/kartoza/sawps/assets/7352963/afc2303a-0314-4e4d-bf06-c2f843969ecc)

Now topper icon for Acinonyx Jubatus is showing
![image](https://github.com/kartoza/sawps/assets/7352963/344c7b7a-ef30-4b51-a8e3-0389dbea2dff)
