### ISSUE TITLE
After selecting 'clear all', species dropdown is empty

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1344]
After selecting 'clear all', species dropdown is empty when I try to select another species
![image](https://github.com/kartoza/sawps/assets/90245715/fc586b59-39f1-475c-b94a-02db3fb03c4b)

**Comment by zamuzakki** [comment]
@LunaAsefaw This is expected since no organisation is selected after clear all.

**Comment by zamuzakki** [comment]
Possible duplicates with #1390
