### ISSUE TITLE
Enhance Permission Handling

### ISSUE THREAD

**Issue by dimasciput** [kartoza/sawps#1354]
- Modify the frontend permission check for chart visibility https://github.com/kartoza/sawps/pull/1348/files#diff-1a83b5895bc62c92945df3a5fcbe6f764f13619ce8359a6f7debe6b1581fe903R207. UPdate this check to the backend using Django's permission framework
- Add permissions to extended group model
- Update the user-api-info endpoint to include the permissions associated with the logged-in user

**Comment by LunaAsefaw** [comment]
@dimasciput do you pass this ticket?
