### ISSUE TITLE
Data-table API bug

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1355]
The report tab has some records missing. The records mostly show in the activity table but are mostly missing on the other report types. For example, Mziki has some elephant records for 2012, as seen below

![image](https://github.com/kartoza/sawps/assets/90245715/09a69726-5773-4ea1-966d-fe399b6d980c)

However, this is not shown in the report even though that property is selected

![image](https://github.com/kartoza/sawps/assets/90245715/b0ff60e5-5639-4ce0-a449-cafe316ad0c8)

This is seen with other species as well, including Panthera pardus. When I followed the API link on the inspect tool for the filter [link here](https://sawps.sta.do.kartoza.com/api/data-table/?reports=Activity_report,Property_report,Province_report,Species_report&start_year=1960&end_year=2023&species=Panthera%20pardus&property=8,9,71,10,4,3,39,40,11,30,82,18,55,7,62,1,12,14,28,29,56,72,73,59,69,64,66,65,5,74,63,2,50,6,51,79,67,78,60,91,70,16,44,90,17,76,48,20,43,19,75,49,33,47,61,42,34,77,46,54,52,53,41,68,13,15,45&organisation=2,12,15,16,6,14,8,17,19,5,21,9,18,13,3,10,4,1,11,20&activity=6,4,3,2,1,5&spatial_filter_values=), It only showed results for Venetia Limpopo even though there are other properties that also have Panthera pardus.

**Comment by zamuzakki** [comment]
PR has been made.
