### ISSUE TITLE
make all charts responsive with the year filter

### ISSUE THREAD

**Issue by tinashechiraya** [kartoza/sawps#1360]

**Comment by tinashechiraya** [comment]
@zamuzakki so basically what I meant is that all the charts need to return results for the years selected in the filters. Some charts were not responding to the filter selections on the years for e.g. when a user decreases or increases the year range some charts were still returning data for other years that were supposed to be excluded . so you could either solve the filtering of the years selected from the backend as the request does contain the year variables or you can do the filtering from the frontend on the charts

**Comment by LunaAsefaw** [comment]
@zamuzakki there is a slight lag between year filter selection and when those years are removed. Not sure if this would be an issue @amyburness @dimasciput 

https://github.com/kartoza/sawps/assets/90245715/df7daa6d-a4ad-40ec-a296-79f50ace957c
