### ISSUE TITLE
Geometry shape of some properties do not show

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1367]
Hluhluwe, Mpamgubwe and Ithala do not show the geometry outline that other properties have when you click on them, for example:
![image](https://github.com/kartoza/sawps/assets/90245715/8f1aa24e-b8dc-4335-9595-b3ce95d2f034)

https://github.com/kartoza/sawps/assets/90245715/316d9069-fac6-4077-b130-78c420979bfa

**Comment by danangmassandy** [comment]
Let's hold this ticket after #851 is finished and deployed.

**Comment by danangmassandy** [comment]
could you please check those properties again @LunaAsefaw? #851 has been deployed to staging.

**Comment by LunaAsefaw** [comment]
@danangmassandy this works, thanks
