### ISSUE TITLE
Charts on the landing page are cut off

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1389]
Cut off on desktop/laptop mode
![image](https://github.com/kartoza/sawps/assets/90245715/b8950b6b-a236-4fd4-9091-54db236ff3de)
Cut off on mobile mode
![image](https://github.com/kartoza/sawps/assets/90245715/38209bae-d6ea-4e19-8e0b-0c8d50180d22)

**Comment by danangmassandy** [comment]
in my laptop, the charts are broken as shown below:
![image](https://github.com/kartoza/sawps/assets/5819076/e758d229-dc8c-4899-9c92-e081514578d7)

**Comment by danangmassandy** [comment]
This should be fixed by PR https://github.com/kartoza/sawps/pull/1479.
