### ISSUE TITLE
Filter issue: After clicking on clear all, none of the species show

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1390]
![image](https://github.com/kartoza/sawps/assets/90245715/4d70d5c3-8418-474c-9385-8c3e6c554470)

**Comment by zamuzakki** [comment]
@LunaAsefaw This is expected since no organisation is selected after clear all.

**Comment by zamuzakki** [comment]
Possible duplicates with #1344

**Comment by zamuzakki** [comment]
PR created.
[1390.webm](https://github.com/kartoza/sawps/assets/7352963/5103b055-8aee-403b-826c-d3973020ac33)

**Comment by LunaAsefaw** [comment]
@zamuzakki are we implementing a tooltip sort of approach for this issue? I see why no species are shown now but I am not sure if it is clear to users. Unless we are leaving this to be discussed in the docs only @amyburness
