### ISSUE TITLE
Filter issue: X button only works when 'select all' is checked

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1391]
This is encountered on Organisations, properties and activities
https://github.com/kartoza/sawps/assets/90245715/c767291e-5ace-4132-957e-1aae9e79354a

**Comment by zamuzakki** [comment]
PR created
[1391.webm](https://github.com/kartoza/sawps/assets/7352963/dcc78134-4224-4f8f-9c26-70fe647d5e44)
