### ISSUE TITLE
Filter issue: When I click on 'Clear all' then try select property, I can't

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1394]
This probably happens because organisations were not selected, but then nothing should be displayed in the dropdown and users should be notified that they need to select an organisation (if they are data scientist, since they see multiple organisations) but if they are organisational members or managers, they do not have the organisation filter option so the properties that belong to that organisation should automatically be displayed in the dropdown and be selectable.
https://github.com/kartoza/sawps/assets/90245715/cc47ff14-c466-4514-8c0d-455703c617aa

**Comment by zamuzakki** [comment]
PR created
[1394-Data Scientist.webm](https://github.com/kartoza/sawps/assets/7352963/068ea6b4-8381-4839-b6f0-cf48610654dd)
[1394-Organisation Member.webm](https://github.com/kartoza/sawps/assets/7352963/ff8b8774-6fb8-46cb-900e-8ef5dd0565c3)

**Comment by LunaAsefaw** [comment]
Can't test this until #1508 and #1503 are fixed.
