### ISSUE TITLE
Filter issue: Sampling report missing

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1397]
Organisational members, managers and data scientists should see the sampling report, which is currently missing
![image](https://github.com/kartoza/sawps/assets/90245715/ba1c5a3c-3d3a-4afa-8aa3-3faa87755291)

**Comment by zamuzakki** [comment]
@LunaAsefaw In this PR, I added Filter related permission and show Permission CRUD page on the admin. Sampling report is now shown for those having permission **Can see sampling report** 

So, technically, we can add the permission to the group that we desire e.g. Data scientist, Organisation Member, and Organisation Manager. And it will show sampling report option
![Prov Data Scientist](https://github.com/kartoza/sawps/assets/7352963/60d703e6-ca64-48aa-ba8b-bda9f0addc45)

When **Can see sampling report** is not added to the group permission, it will be hidden.
![No sampling report permission](https://github.com/kartoza/sawps/assets/7352963/74ed7ad9-7285-4585-b39a-8d37f9d49403)
