### ISSUE TITLE
Population estimate chart is inaccurate

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1411]
The data:
![image](https://github.com/kartoza/sawps/assets/90245715/0a7df285-c5f5-439f-bcc5-bbc27485b2cc)

The output:
![image](https://github.com/kartoza/sawps/assets/90245715/6684e3c4-3f62-4292-9206-8faf4edcc07b)

The graph only accounts for rough guestimate when there are other population estimates and how is the value at the center derived?

**Comment by LunaAsefaw** [comment]
Another example on the issue:
![image](https://github.com/kartoza/sawps/assets/90245715/209e1a91-447b-433d-8cb4-93c7d182f00d)
![image](https://github.com/kartoza/sawps/assets/90245715/b5ca8bcc-6e39-48f2-8905-fcc03309c8e4)

**Comment by amyburness** [comment]
@LunaAsefaw this is correct for total count per estimate is a sum of the counts for each estimate category and can be applied for any number of properties and years.

**Comment by zamuzakki** [comment]
@LunaAsefaw @amyburness is this still an issue?

**Comment by zamuzakki** [comment]
@LunaAsefaw This is how it looks like on my local. The reports and charts are synced.
Let's re-test this once it's deployed on staging.
![image](https://github.com/kartoza/sawps/assets/7352963/a77a2fd0-0b8a-4ca2-8236-79e101e71063)
![Screenshot from 2023-11-03 10-28-00](https://github.com/kartoza/sawps/assets/7352963/f289bfcf-adb1-435f-b43b-cae27f71eafe)
