### ISSUE TITLE
Documentation fixes

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1412]
1. Consistency in listed points ( if starts with 'click', continue with 'click' on the other points or use 'the ABC button provides..')
![image](https://github.com/kartoza/sawps/assets/90245715/656665c1-e55d-4b7c-b685-c93feca237f6)
2. Reference to a page should link to that markdown. For example, login and registration both have a whole markdown on them, use cross-linking (eg [registration](registration.md) so when people click on it, they can navigate to that page
![image](https://github.com/kartoza/sawps/assets/90245715/dc564927-13f0-4b9d-9508-e4ce0dd80ab7)
4. Avoid using 'our', 'the' is preferable
![image](https://github.com/kartoza/sawps/assets/90245715/b5064fb9-2d16-41f2-8c88-dc85d51e8b71)
5. Different pages should be on different markdowns, eg help and contact md should be help.md and contact.md since these are different tabs
![image](https://github.com/kartoza/sawps/assets/90245715/f9cfe4e6-60ad-4a6f-9e0b-4c61f5dcc229)
6. Do not use contractions, eg you are instead of you're.
![image](https://github.com/kartoza/sawps/assets/90245715/714f0d07-bb91-4f09-9578-020c62768af4)
7. Instead of 'you', write 'user': eg instead of 'where you can do this', it shold say 'where the user can do this'
![image](https://github.com/kartoza/sawps/assets/90245715/24fb56a6-2f37-45e9-8a77-8d6683465f3c)
8. Every title needs a short description underneath it. If there is a second title under the primary title that does not have a description underneath it, get rid of the second title
![image](https://github.com/kartoza/sawps/assets/90245715/bc55f018-b078-407c-8522-dcdd2356bc88)
9., Don't describe something that will have its own markdown, you can cross-link it instead. For example, instead of explaining everything that can be found on the 'About page', explain that they can click here to get to the about page but you don't need to describe what is there since you can just link to the About.md where they can navigate to that section and read all about it.

These notes are for all the sections in the manual, not just the landing page.

**Comment by LunaAsefaw** [comment]
@amyburness anything else you'd like to add here?

**Comment by LunaAsefaw** [comment]
@ketankartoza look at this PR from Amy on the changes she made for more reference on this 
https://github.com/kartoza/sawps/commit/f10c031351e3525be91e058ac251dc4901f0bde6

**Comment by Jeremy-Prior** [comment]
@LunaAsefaw For point 1, it is intentional to use different words and language so that the content does not become monotonous and users disengage from it
