### ISSUE TITLE
Text on the landing page charts is not legible

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1413]
The goal:
![image](https://github.com/kartoza/sawps/assets/90245715/35329204-d9ca-42eb-847a-8fcfd0d5cb08)
Currently the text clashes with the dark background:
![image](https://github.com/kartoza/sawps/assets/90245715/8976892e-80f7-4d53-a7fa-eeb9d8fe0481)

**Comment by danangmassandy** [comment]
updated with white x/y axis label and legend:
![Screenshot_4759](https://github.com/kartoza/sawps/assets/5819076/15c83b68-c8c5-4003-90fc-d8ad9d2dfdca)
