### ISSUE TITLE
Add report topper to downloaded report 

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1414]
This is downloaded when the user clicks on 'Download visualisation; on the charts tab
![image](https://github.com/kartoza/sawps/assets/90245715/24653dcd-716b-4d47-9b64-9286ad46e6eb)
This needs to be included at the top of the report
![image](https://github.com/kartoza/sawps/assets/90245715/13ab03fb-fbb0-44a4-bcc5-327b25b36068)

**Comment by zamuzakki** [comment]
This is done in https://github.com/kartoza/sawps/pull/1557.
