### ISSUE TITLE
Chart and report issue: Inconsistency in data shown

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1426]
This is the data shown in the report: there are two Free State properties and one Limpopo property.
![image](https://github.com/kartoza/sawps/assets/90245715/b1f1e672-92b7-4e4c-a332-f52df5233e89)

But the province charts only show Western Cape
![image](https://github.com/kartoza/sawps/assets/90245715/71d504c9-3628-481b-9fe8-f45138dd4422)

This is also seen on the other charts that show the Western Cape property
![image](https://github.com/kartoza/sawps/assets/90245715/d3bf1bf0-bc0f-4063-8819-ac16876bc88b)

The other issue is that Western Cape does indeed have a cheetah record but that is not seen in the first image showing species report.

**Comment by zamuzakki** [comment]
Reports and Charts should now be consistent.
![reports](https://github.com/kartoza/sawps/assets/7352963/04f134b5-f4ad-468a-b7ee-187693ee83e9)
![Screen Shot 2023-11-06 at 12 57 15-fullpage](https://github.com/kartoza/sawps/assets/7352963/a3a8f75f-b0b0-4123-9ae0-cce6d117f8f8)
