### ISSUE TITLE
Filter issue: When province report is deselected and then user tries to sleect it again, they can't

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1430]
As seen in the video, this issue is only encountered with Province because I turned another layer on and off and it was okay.
https://github.com/kartoza/sawps/assets/90245715/d45b8663-9acc-4890-85fe-541dd32e9c6a

**Comment by zamuzakki** [comment]
PR created:
[1430.webm](https://github.com/kartoza/sawps/assets/7352963/c52ea3e8-ab7e-4d6d-8858-b7619110079a)
