### ISSUE TITLE
There are some organisations in the header that do not exist in the backend

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1433]
![image](https://github.com/kartoza/sawps/assets/90245715/2a03ca27-fe22-40ee-b65c-6f9ed98c3134)
The organisations highlighted below are not organisations that are registered:
![image](https://github.com/kartoza/sawps/assets/90245715/9c401b02-1db8-401e-aa1b-69ed04fb76d6)

I think this is happening because the code is separating the data by comma so where there is a comma, it counts it as a new organisation,  hence 'Department of Environment and Nature Conservation, Northern Cape Province' is taken as 'Department of Environment and Nature Conservation' then 'Northern Cape Province' as another. When you count all of these that have been incorrectly divided by commas, they add up to 8 and there are only 20 organisations on the site so the 28 seen on the header is probably because of these 8

**Comment by LunaAsefaw** [comment]
Linked to #1342

**Comment by zamuzakki** [comment]
PR created.

**Comment by zamuzakki** [comment]
Closed on duplicate. Will use #1342 instead.
