### ISSUE TITLE
Remove unnecessary horizontal scroll on province report

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1488]
![image](https://github.com/kartoza/sawps/assets/90245715/d1b18cfb-a80b-4c65-b2fb-1b362f4e1fb6)

**Comment by zamuzakki** [comment]
No horizontal bar in the Province report
![province](https://github.com/kartoza/sawps/assets/7352963/b60bdd46-93bb-41b6-bcc6-a6b100ba048d)
