### ISSUE TITLE
Editting or deleting records in the admin site shows error 500

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1506]
I edited population status, population estimate category and survey method for my Luna's farm cheetah record but it gave me Server error 500. However, it still committed my change even though the error is displayed. I also deleted 'Close' from the open close system table but it showed server error 500 but still deleted 'Close'. However it is now back again, I don't know why

**Comment by dimasciput** [comment]
First issue has been addressed, regarding open close issue, please meet with @zamuzakki .

**Comment by zamuzakki** [comment]
The 'close' issue was caused by CSV population uploader creating Open/Close system from CSV upload, if it does not exist. This is not what we want.
I updated the uploader to restrict the Open/Close system. If it does not exist, it will show error instead of creating a new one.
