### ISSUE TITLE
Property filter missing from the filters

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1508]
![image](https://github.com/kartoza/sawps/assets/90245715/53f8b265-9770-473b-aad8-d6f7b1f33649)

**Comment by zamuzakki** [comment]
There is a permission named "Can view property filter", assigned to groups, which currently is used to display property filter.
If all user is expected to have that permission, which means property filter will always be shown, we can remove the permission checking @LunaAsefaw
