### ISSUE TITLE
Make sub-population total fields editable

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1525]
These fields should function the same way as the 'total count' field. If the adult female or male is inputted then the total adult then it is editable but if the male or female field is left as 0 then it should be editable. The only difference in behaviour between this and the total count one is that 0 is allowed as an answer for the selected fields while it is not allowed for 'Total Count'
![image](https://github.com/kartoza/sawps/assets/90245715/1ce91a13-af52-4582-8e11-d0ab3c02d9c5)

**Comment by danangmassandy** [comment]
@LunaAsefaw I'll also store these fields to the database.
