### ISSUE TITLE
Submit another record option

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1526]
I think the user should have the option to submit another record by clicking on a button next to ok in case they would like to add another record for the same property
![image](https://github.com/kartoza/sawps/assets/90245715/89643d41-023d-43b5-8b52-e81764e6fdd7)
Currently user is sent to the explore page after clicking ok then they go to upload then select the same property again. It might be user-friendly to reduce some of the clicking the user has to do.

**Comment by LunaAsefaw** [comment]
https://github.com/kartoza/sawps/assets/90245715/9c2162e4-f952-4a63-99ae-546f5627e450

**Comment by danangmassandy** [comment]
@LunaAsefaw this has been implemented via #1696
