### ISSUE TITLE
Population trend graph needs to be moved to the trends tab

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1571]
![image](https://github.com/kartoza/sawps/assets/90245715/41fdaae2-72bd-44af-a7da-bd19ff9d0fb0)
linked to #989

**Comment by danangmassandy** [comment]
@LunaAsefaw is this ticket still needed?

**Comment by LunaAsefaw** [comment]
no @danangmassandy thanks, it is implemented already
