### ISSUE TITLE
Add people to organisation isn't working

### ISSUE THREAD

**Issue by Mattyc84** [kartoza/sawps#1606]

**Comment by LunaAsefaw** [comment]
Nothing happens when you add members. No error or success message or email received 
https://github.com/kartoza/sawps/assets/90245715/dc6583dc-e33b-47f3-9421-0e52b00ca834

**Comment by LunaAsefaw** [comment]
@Mattyc84 this is now fixed, thanks for notifying us 
![Uploading image.png…]()
