### ISSUE TITLE
Side map pop up broken again

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1609]
This is what it shows
![image](https://github.com/kartoza/sawps/assets/90245715/c7594814-5fa7-4914-b95d-e5fa0b782756)

When there is data for the property:
![image](https://github.com/kartoza/sawps/assets/90245715/37dbb54c-3050-40a9-8c94-026041ec97a3)

What is expected:
1. A bar chart showing the total population on that property per year (the title should include species name).
2. A bar chart showing activity count per activity type for a specific year (the title should include species name and year)

**Comment by danangmassandy** [comment]
Preview:
![image](https://github.com/kartoza/sawps/assets/5819076/9f1ded4c-55b3-4538-9972-0b526364f7ed)

@LunaAsefaw I've changed the first chart to bar chart, are the charts displayed correctly as expected?
