### ISSUE TITLE
Total area vs total available area chart needs to be moved to the trends tab

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1611]
![image](https://github.com/kartoza/sawps/assets/90245715/4e3d7205-225b-4e5f-9570-971ddd90df5a)

**Comment by danangmassandy** [comment]
TODO:

- [ ] Fix chart data API for national level of Total area vs area available
- [ ] Fix chart data API for each property of Total area vs area available
- [ ] Add charts to trends tab - national + property sections

**Comment by danangmassandy** [comment]
@LunaAsefaw @amyburness could you confirm again that we needs below chart for each property in the trends tab?
![image](https://github.com/kartoza/sawps/assets/5819076/33a253c8-17a1-4e1c-86de-70cd56a9ecb8)
