### ISSUE TITLE
The sticky button on the reports tab is overlapping the table

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1622]
![image](https://github.com/kartoza/sawps/assets/90245715/801dad2e-63f1-4fa3-bf73-bc6c94b3999c)
I know we mentioned making the button float so the user does not have to scroll to the bottom to get the data but this also blocks some of the data so please make the button sticky with some buffer from the tables

**Comment by zamuzakki** [comment]
This has been addressed.
![image](https://github.com/kartoza/sawps/assets/7352963/9017d94e-dd94-4953-b3c6-2bb281db056b)
