### ISSUE TITLE
Scrollbar on map view 

### ISSUE THREAD

**Issue by dimasciput** [kartoza/sawps#1628]
![image](https://github.com/kartoza/sawps/assets/1979569/585e585b-f3df-4d36-b69c-f1688e0868f8)

The scrollbar now appears on the map view after the responsive updates, please fix this

**Comment by LunaAsefaw** [comment]
![image](https://github.com/kartoza/sawps/assets/90245715/b52c6e71-187c-4772-99e5-09d2acec528b)
