### ISSUE TITLE
Add if_other fields in the backend

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1635]
![image](https://github.com/kartoza/sawps/assets/90245715/a5675d0e-839e-43c7-8ce3-43e94907c4cb)

![image](https://github.com/kartoza/sawps/assets/90245715/7703a449-a352-4291-9f85-0f4b765a7711)

Please make sure it is assigned to the correct fields for the data upload too

**Comment by LunaAsefaw** [comment]
@danangmassandy I can't seem to find it on the django site 

![Image](https://github.com/kartoza/sawps/assets/90245715/3c51e2c9-b150-482c-bb0b-a5be0ff01b3d)

**Comment by danangmassandy** [comment]
@LunaAsefaw the fields are 'Survey method other' and 'Population estimate category other'. Perhaps, I will add help text below the fields.

**Comment by LunaAsefaw** [comment]
Works

![Image](https://github.com/kartoza/sawps/assets/90245715/e89aaba4-01c6-4b36-aa5c-dcbcb4220efb)


![Image](https://github.com/kartoza/sawps/assets/90245715/8ec5b233-0af9-4010-b920-da263b467a7b)
