### ISSUE TITLE
Spelling Mistake on Django Admin SIte

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/sawps#1650]
In the `Add Taxon` table, it says 'Common name varbatim'. Varbatim is not a word and should be updated to 'verbatim'.

![image](https://github.com/kartoza/sawps/assets/100694811/a6bf2b5c-5a3c-4818-bf29-ff218044af7c)

**Comment by LunaAsefaw** [comment]
@ketankartoza can you work on this?

**Comment by ketankartoza** [comment]
@LunaAsefaw Sure I will.
