### ISSUE TITLE
Province filter on trends tab

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1654]

**Comment by danangmassandy** [comment]
hi @LunaAsefaw, when adding this filter, the affected sections would be:

- Provincial section: show only selected provinces
- Properties section: show properties in selected provinces

I guess this province filter is also multi select?

**Comment by LunaAsefaw** [comment]
but remember the data used to train the model is all the data, this is just to select what can be visualised. Please don't forget that this tab still needs to be responsive based on filters (so if two are selected vs eight, how is the placing of the charts going to be affected and so forth)
