### ISSUE TITLE
Report based on species and property perspective

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1655]
We are now splitting the report tabs into Species report and Property report. Species report is the existing report tab, it just needs to be renamed to species report. The newly added tab 'Property report' functions the same way as the species report, except this is where people select properties and view all associated data for all species on those selected properties. For example, if I select Luna's property, I can see all the species found on that property and select more than one property at a time.
The image below is an idea of what the users may see, please include property name and shortcode, organisation name and shortcode and year on all of the different reports
![image](https://github.com/kartoza/sawps/assets/90245715/111ca1b4-960b-4ef8-b193-09b78e49a408)

**Comment by zamuzakki** [comment]
I have confirmed to @LunaAsefaw that the only difference between Species Report and Property Report is Species Report could only select 1 species.
