### ISSUE TITLE
Cant scroll to bottom of the page

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#1666]
![image](https://github.com/kartoza/sawps/assets/178003/b8733291-3673-4653-b7c2-d3c6d928b891)

**Comment by LunaAsefaw** [comment]
@danangmassandy similar situation here 
![image](https://github.com/kartoza/sawps/assets/90245715/978e31b1-d7bf-4a49-9466-3c96b5d5b172)

**Comment by danangmassandy** [comment]
@dimasciput is the nav bar always sticky to the top? if yes, we may need to make it sticky for other pages like about, help, contact
