### ISSUE TITLE
"lower_ci"  and "upper_ci" do not show for some species

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1670]
![image](https://github.com/kartoza/sawps/assets/90245715/dfdb6ee2-d459-428c-a662-165378361a2b)
Additionally, could the labels on the x-axis be angled the same way? I understand that they are angled when there is lots of data so should we make all the labels angled for consistency? Any advice @dimasciput?

**Comment by danangmassandy** [comment]
@LunaAsefaw this is the data from national trend of Panthera leo. I think the lower_ci and upper_ci are too close with the sum_fitted value. Could you try to plot this data using Tim K's graph code in R studio?
```
"national_trend": [
        {
            "year": 2010,
            "sum_fitted": 8.43,
            "lower_ci": -7.09,
            "upper_ci": 23.94
        },
        {
            "year": 2011,
            "sum_fitted": 140.35,
            "lower_ci": 121.36,
            "upper_ci": 159.33
        },
        {
            "year": 2012,
            "sum_fitted": 340.14,
            "lower_ci": 321.83,
            "upper_ci": 358.45
        },
        {
            "year": 2013,
            "sum_fitted": 450.7,
            "lower_ci": 431.78,
            "upper_ci": 469.62
        }
    ],
``` 

This is the attached csv data for Panthera leo.
[270_panthera_leo.csv](https://github.com/kartoza/sawps/files/13434372/270_panthera_leo.csv)

**Comment by danangmassandy** [comment]
@LunaAsefaw for this ticket, let me try to allign the years in the x axis label

**Comment by danangmassandy** [comment]
Updated @LunaAsefaw.
Previews:
![Screenshot_4824](https://github.com/kartoza/sawps/assets/5819076/f6ebca40-f907-4199-99ce-7322c1d82c3a)
![Screenshot_4825](https://github.com/kartoza/sawps/assets/5819076/90e618f6-a872-4555-977b-c44a206bae18)
![Screenshot_4826](https://github.com/kartoza/sawps/assets/5819076/d8ad7af9-316b-458d-a49f-c9a48ed419ca)
