### ISSUE TITLE
Include time on the topper of trend

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1673]
Since the data on the chart is updated on a specific time interval, please indicate the time
![image](https://github.com/kartoza/sawps/assets/90245715/82d2aa33-ff63-4f96-948f-bdb9e8e746f4)

**Comment by LunaAsefaw** [comment]
"These trend models were created on (date of last update to trend charts).." instead of 'This report..'

**Comment by danangmassandy** [comment]
Preview:
![image](https://github.com/kartoza/sawps/assets/5819076/789092ab-f052-47f7-b2d7-4cd73229c5d3)

if there is no data:
![image](https://github.com/kartoza/sawps/assets/5819076/cf7a6869-a328-4098-9486-c97d40aa2bfe)
