### ISSUE TITLE
Include the parent farm in the property upload process

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1674]

**Comment by danangmassandy** [comment]
@LunaAsefaw based on our discussion (with Jeremy too), I will implement the following:

- Update style to include parent_farm at zoom level 9
- Include parent_farm in the parcel selections
- Add type in the parcel list selection to indicate the parcel type (erf, holding, farm_portion, or parent_farm)

**Comment by LunaAsefaw** [comment]
confirmed:
![image](https://github.com/kartoza/sawps/assets/90245715/1c9a78b3-25fd-4a7a-b2d2-32821d1b16e0)

**Comment by danangmassandy** [comment]
@LunaAsefaw based on discussion during sprint planning yesterday, we will includes smaller parcels when a Parent Farm is selected. Is this correct? could you please create a new ticket for this?
