### ISSUE TITLE
Only the species report is downloaded

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1684]
I have selected all report types but only this is shown. However, I think this might be caused by user role issues because my admin account works without issues.
Regardless of what the user role is, what is displayed on the reports tab needs to be contained in the downloaded file
https://github.com/kartoza/sawps/assets/90245715/ff590347-d472-4926-8d9e-705f0161d421

**Comment by zamuzakki** [comment]
I created non admin user with role organisation member (Cape Nature), but I can download all report, hence cannot reproduce the issue.
 I have asked @LunaAsefaw to retest it.
