### ISSUE TITLE
No charts generated for data consumers and organisational members

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1685]
This is what the charts tab looks like even though lots of records are shown on the report tab (this is for user: luna2)
![image](https://github.com/kartoza/sawps/assets/90245715/cc75717d-176b-4e9c-b339-0eb8f1d9a3ca)

**Comment by zamuzakki** [comment]
@LunaAsefaw This happened because we haven't added permission to the National data Consumers group.
