### ISSUE TITLE
Deleting a user from the admin site causes an error.

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/sawps#1693]
If an administrator removes a user via the admin site (using either deletion method), the user is removed but the site returns an error message. If the admin had the list of users open in another tab simultaneously and refreshes they can see the success message of the user being deleted.

[delete-user-error.webm](https://github.com/kartoza/sawps/assets/100694811/eaf64812-d120-4b31-a083-1632b486f22f)

**Comment by LunaAsefaw** [comment]
@zamuzakki I deleted a user, I got an server 500 error but it still deleted the user so this issue seems to still exist

**Comment by danangmassandy** [comment]
@LunaAsefaw the delete user should be fixed by above PR.
