### ISSUE TITLE
Bug with filter: After clear all then reselecting, nothing works beside province report

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1712]
As you can see, when I select species and show activity, there is data. However, when I clear all my filters then select all the data again, all the data that was previously shown now disappears

https://github.com/kartoza/sawps/assets/90245715/985f54c0-6242-4d5f-b118-8db7070b0f3d

**Comment by LunaAsefaw** [comment]
This seems to be happening only on the report tab. I think it has something to do with the activity filter because after clearing all, the activity filter is cleared. When I select all the activity filters, the data is showing. But this does not happen on the map or charts because t shows the charts even if activity is not selected

**Comment by zamuzakki** [comment]
As per our discussion in today's Sprint Planning:
- By default, all Activity will be deselected.
- By default, reports will show all records, be it having activity or not.
- User then select any activity to have more detailed reports.

**Comment by LunaAsefaw** [comment]
@zamuzakki moving this back to 'to-do' as per discussion yesterday

**Comment by danangmassandy** [comment]
@LunaAsefaw is there anything left todo in this ticket? I tried clear all the filter, then I select all organistions -> select 1 species -> select all reports. It can display all the reports.
