### ISSUE TITLE
Issue with Kruger polygon

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1735]
This is what is uploaded on the site: 
![image](https://github.com/kartoza/sawps/assets/90245715/a8caa485-891f-4f8f-b76e-e1f4a8a83b1c)

This is what I uploaded: 
![image](https://github.com/kartoza/sawps/assets/90245715/50e0ef81-3fb9-4bda-a2ba-363b6dc503f2)
[kruger.zip](https://github.com/kartoza/sawps/files/13476262/kruger.zip)

**Comment by danangmassandy** [comment]
@LunaAsefaw the missing parcels seems were already used by property 'Test Judith'.

![image](https://github.com/kartoza/sawps/assets/5819076/9524001b-f03e-4ee2-aa44-b2f8f51eccf2)

**Comment by LunaAsefaw** [comment]
Closing this because a new ticket has been created focussing on the new problem #1866
