### ISSUE TITLE
Activity filter on chart and map page not working

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1738]
When you select just these two activity types in the reports page, the data is filtered to only display those that meet the requirement:
![image](https://github.com/kartoza/sawps/assets/90245715/725be84a-7366-49b8-854e-ed238a7f3ca1)

However when I select the same filter on the chart or map tab, nothing changes and all the records for the species for that year are shown (regardless of whether they meet the requirement or not):

**Comment by danangmassandy** [comment]
hi @LunaAsefaw could you confirm which charts that need to be filtered with activity?
