### ISSUE TITLE
Property filter missing on charts and maps

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1739]
![image](https://github.com/kartoza/sawps/assets/90245715/5eba4a50-9739-4cce-844c-38e6526fe5c9)
![image](https://github.com/kartoza/sawps/assets/90245715/b0e7b175-29c1-4662-a887-6236c55b4350)

**Comment by zamuzakki** [comment]
PR for this has been merged, but not yet deployed.
