### ISSUE TITLE
Data consumer should not see granular property data on the map

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1752]
I can see which property has the select species and what the count on each property is. The data consumer should only see the choropleth map.
![image](https://github.com/kartoza/sawps/assets/90245715/c19c2111-8aa2-4a89-bc24-6ebb022eeeb2)

**Comment by danangmassandy** [comment]
@LunaAsefaw could you let me know which logged in user for this Data Consumer?

**Comment by danangmassandy** [comment]
@luna could you confirm that this ticket only requires permission configuration for Data Consumer Group in staging?
