### ISSUE TITLE
An organisational member who only has one organisation does not need to see the other organisations in the drop down

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1815]
This user is only assigned to CapeNature so the other organisations are irrelevant. If the user has more than two organisations, please display just the organisations they belong to. Otherwise, please remove the filter or grey it out
![image](https://github.com/kartoza/sawps/assets/90245715/e5d01f6a-1912-4a24-879a-a7c5f6d4fc54)

**Comment by danangmassandy** [comment]
@LunaAsefaw could you retest this ticket? I think this issue has been fixed by my PR #1808
