### ISSUE TITLE
Server error when deleting property

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/sawps#1843]
When I delete following property (in my local), there is exception from easy audit signal.
![2023-12-12_09-27](https://github.com/kartoza/sawps/assets/5819076/cbb4b9db-6871-471e-a310-77dd3ea87eef)

Exception:
![image](https://github.com/kartoza/sawps/assets/5819076/dfda73f8-735a-4eb2-bba6-86b1c69b3e41)

**Comment by LunaAsefaw** [comment]
@danangmassandy I get this error when I delete a property, although it does remove the property
![image](https://github.com/kartoza/sawps/assets/90245715/6bfc904d-c81b-4f55-8cb3-944ebe091d71)

**Comment by LunaAsefaw** [comment]
Still experiencing this issue @danangmassandy 

![Image](https://github.com/kartoza/sawps/assets/90245715/f851c303-e712-4ca3-85c1-14b3e54a23db)
