### ISSUE TITLE
GeoJSON upload does not work on Windows

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1861]
When users click on the upload option for property upload, GeoJSON files are not show displayed for them to choose data from and if you select it (only after selecting all data so invalid formats are also shown), it just shows an inactive dialogue box. This is only happening on Windows at the moment and works perfectly for Linux

https://github.com/kartoza/sawps/assets/90245715/aca836b3-4331-488c-8b45-13942de6c168

**Comment by danangmassandy** [comment]
This is the limitation of the uploader library at the moment. I'll check if there is workaround for geojson in windows. One of the alternative is to rename the geojson file to .json file
