### ISSUE TITLE
Change boundary colour

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1864]
When users are uploading property data, a white line is generated over the selected parcels and this works well when zoomed in. However, when users zoom out (when you have a large area), the white boundary does not show well with the white base map. This happens on light and dark mode
![image](https://github.com/kartoza/sawps/assets/90245715/3e801f3c-79e4-4e81-9982-8223c7542bb2)
![image](https://github.com/kartoza/sawps/assets/90245715/01581f4a-14ee-49cf-9be7-0021a2997821)

**Comment by danangmassandy** [comment]
I've changed the colour to orange. Please check the below screenshots, what do you think @LunaAsefaw?
![2024-01-12_10-41](https://github.com/kartoza/sawps/assets/5819076/a3cee8ee-f6c7-43ef-b14e-4ff33eb9ad51)
![2024-01-12_10-40](https://github.com/kartoza/sawps/assets/5819076/7f5f4ffa-fa8f-41bb-b4e8-641e5cb0572f)

I think I'll also use this colour for ticket #1879, the original boundary from property.

**Comment by danangmassandy** [comment]
how about purple? The previous color is not good match with properties layer (red color):
![image](https://github.com/kartoza/sawps/assets/5819076/c5dae5e6-80ba-4679-be3f-4d2f35176445)

**Comment by LunaAsefaw** [comment]
@danangmassandy yes this is very visible, thanks

**Comment by LunaAsefaw** [comment]
Closing ticket

![Image](https://github.com/kartoza/sawps/assets/90245715/54a0f033-1ffc-4fa5-bf31-6fb163f78c54)
