### ISSUE TITLE
Update property

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1865]
Overtime, some of the boundaries might change (grow or become smaller). When users update property boundaries, it should not create an error that the parcels are already being used by another property (since the property it is referring to is itself). For example, if KNP uses parcels a and b but I update this so that it is parcels a,b and c, it should not produce an error that a and b already belong to another property if the property is KNP (since that is the property that I am updating and should just update the property to parcel a,b and c). That error should only occur is parcel c (the new parcel that I am updating KNP with) actually belongs to another property

**Comment by danangmassandy** [comment]
@LunaAsefaw can we close this ticket? we do not check the used parcel anymore because ticket #1920 has been implemented.
