### ISSUE TITLE
Duplicate in manual

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1872]
The additional resource section is repeated
https://github.com/kartoza/sawps/assets/90245715/d89ffc55-2da5-4591-8376-01d4c707184b

**Comment by Jeremy-Prior** [comment]
That is intentional

**Comment by ketankartoza** [comment]
@LunaAsefaw, I have moved this ticket to the needs review column. Please close this ticket as done. Thanks!!
