### ISSUE TITLE
Storing reminders

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1882]
I created reminders for 11 am and 12 pm and was notified of them but when I return to my profile, they are no longer showing (they used to show with the status 'passed' before)
![image](https://github.com/kartoza/sawps/assets/90245715/70b4167e-8640-4879-ab11-ca99353e6622)

**Comment by dimasciput** [comment]
I couldn't reproduce this, it might be because you have a different active organization than the one you created a notification for.

**Comment by LunaAsefaw** [comment]
@dimasciput you were right, I changed organisations. Thanks
