### ISSUE TITLE
Inconsistency in data between report and chart for data consumer

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1917]
Planned hunt and euthanasia do not match and when I looked at the data as a data scientist, the chart corresponds, which means the data consumer report is not adding up  as intended but I also thought this might be an issue with user role (provincial or national) but I am logged in as national on both and assigned to the same organisation
Chart seen on both accounts:

![Image](https://github.com/kartoza/sawps/assets/90245715/5d9ddffa-4801-4431-b9db-ea3897e5c3f8)

However, this is the report for the data consumer:

![Image](https://github.com/kartoza/sawps/assets/90245715/cb54ee25-c965-4a5b-a17a-2b352a944c68)

This is the report for the data scientist which matches the chart:

![Image](https://github.com/kartoza/sawps/assets/90245715/7d36582b-ad14-41cf-a5fe-705b5b827255)

**Comment by LunaAsefaw** [comment]
Update on the issue

https://github.com/kartoza/sawps/assets/90245715/3e9f3a8b-9fbd-4cec-9a2b-a19a0183d536

**Comment by LunaAsefaw** [comment]
Perhaps linked to #1747

**Comment by danangmassandy** [comment]
I will check this ticket on next Monday and let you know about the finding. @LunaAsefaw

**Comment by danangmassandy** [comment]
@LunaAsefaw I could not reproduce this issue, I created a new user and joined CapeNature as National Data Consumer. This is what I see with this new account.
![2024-02-21_12-35](https://github.com/kartoza/sawps/assets/5819076/fba81523-cc6f-4d75-8811-3032d39436f4)
