### ISSUE TITLE
We need data model for static map layers

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#416]
Two types of layers we will support:

vector xyz tiles
raster xyz tiles (for http://aerial.openstreetmap.org.za/)
There will be two modalities:

cached layers - used for static layers
dynamic layers - used for user generated content
Note that WMS is mentioned in the original brief but will be descoped,

In some cases the Vector tiles will contain multiple layers.

static layer styles available here:  https://github.com/kartoza/sawps-cartography
@Jeremy-Prior can you organise the DB layers for this and share?

![Image](https://github.com/kartoza/sawps/assets/77841514/4410220a-d03c-455f-a278-d81247c3e2f8)

The static layers include:

- Rivers
- Roads
- Ecosystem type
- Biodiversity areas
- Protected areas
- Cadastral boundaries
- Place names

**Comment by Jeremy-Prior** [comment]
DB has been shared and the static layers have been implemented onto staging site.
![issue416_1](https://github.com/kartoza/sawps/assets/100694811/4f325bde-b787-4860-b73e-ca5f3f25bb2e)

Raster imagery is also present:
![issue416_2](https://github.com/kartoza/sawps/assets/100694811/22f1ebd5-9e4a-492b-9dbc-6853e94826cb)
