### ISSUE TITLE
We need a Landing Page

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#487]
We need the logged in Landing page for a user
![image](https://github.com/kartoza/sawps/assets/77841514/c4a06b9d-7b10-434d-a607-b1651585359b)
see figma mockup below
https://www.figma.com/proto/T6JEAAXTWzA9OIfAQe3iW7/SANBI?type=design&node-id=1347-27096&scaling=min-zoom&page-id=643%3A2824&starting-point-node-id=744%3A5022&show-proto-sidebar=1

**Comment by ThiashaV** [comment]
Once logged in you are redirected to a landing page that matches the landing page design on the figma board referenced in the ticket. 
![image](https://github.com/kartoza/sawps/assets/98025261/b4cd6b19-8981-41df-9345-799827da9ede)
![image](https://github.com/kartoza/sawps/assets/98025261/41f06448-9543-4f76-9d06-a43452c78cb1)

**Comment by amyburness** [comment]
@DONOTFORGET-BYTE 
Update the chart grey background to blend into the black background with a gradient. as per the Figma design. 


![Image](https://github.com/kartoza/sawps/assets/77841514/56871a57-7a50-49e6-85f1-14d7a30a4783)

**Comment by amyburness** [comment]
@tinashechiraya This is the design there is a gradient from black to grey on the site it is just a block with a line from black to grey no gradient. 
design (needs to be)
![image](https://github.com/kartoza/sawps/assets/77841514/0520cad1-010c-4f5b-82ef-12a255100d19)
site (what it looks like now)
![image](https://github.com/kartoza/sawps/assets/77841514/04ae0df3-6685-4fb9-93bc-c15ab5ff0b6a)
