### ISSUE TITLE
Make email better 

### ISSUE THREAD

**Issue by dimasciput** [kartoza/sawps#510]
Currently, emails sent with HTML tags are still being displayed. We need to send emails with Django send_mail function and use the parameter **html_message**.

Let's clean up the email template, and add a header and an icon as shown in the screenshot below.

![image](https://github.com/kartoza/sawps/assets/1979569/b207b8f5-d75a-4979-96fa-6ad0a6483389)

**Comment by amyburness** [comment]
Updated for the registration email check ticket #962
