### ISSUE TITLE
Add a dark light map mode

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#528]
Can we add a button to the interaction panel to swap between dark and light mode? 
can it have a tooltip on hover that says (Swap between light and dark mode)
![image](https://github.com/kartoza/sawps/assets/77841514/70ef179c-0b49-40f3-97cd-2770cbcfa08d)

**Comment by ThiashaV** [comment]
Light mode:
![image](https://github.com/kartoza/sawps/assets/98025261/aadca5ee-7c4e-4eda-a525-05eeed92ced8)
Dark mode: 
![image](https://github.com/kartoza/sawps/assets/98025261/dd7ff922-41fa-4fd3-84dc-b9f40d3c8167)
Tooltip on hover that says toggle dark/light mode:
![image](https://github.com/kartoza/sawps/assets/98025261/6ca31f0c-fb24-4829-a873-c73ac798aa95)
![image](https://github.com/kartoza/sawps/assets/98025261/d1ad3d00-0fd1-469f-9cc9-a31ec4b892cf)
