### ISSUE TITLE
Make Print and base-map buttons work on interactions panel 

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#542]
![image](https://github.com/kartoza/sawps/assets/77841514/9ffceb1b-3c68-4e55-bc1f-1f7c4c2dd298)

Can we make:
- the print icon button just prints a screenshot of what ever is currently on the map canvas. 
- the basemap switch between 
 - NGI imagery
 - No base imagery
 - OSM base map (Do you need any thin for this one?)

**Comment by ThiashaV** [comment]
OSM is no longer a part of the system

**Comment by ThiashaV** [comment]
The print icon saves a screenshot of whatever is currently on the map canvas:
![image](https://github.com/kartoza/sawps/assets/98025261/66865c8a-3ecc-4138-95bf-d8858bb80e53)
![image](https://github.com/kartoza/sawps/assets/98025261/41baee94-378e-499a-826e-4283773f701b)

The base map switch between is enabling or disabling the NGI imagery. without the NGI imagery enabled, there is no basemap.
![image](https://github.com/kartoza/sawps/assets/98025261/4acc81b0-d50d-45b4-bc0d-845925ae192f)
![image](https://github.com/kartoza/sawps/assets/98025261/b7f32aa1-f355-4dd2-a9ba-cc67cdae785b)
