### ISSUE TITLE
Show Parcel CName in Popup when mouse on hover

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/sawps#564]
We need to show a popup that display cname when mouse is hovering on top of the parcel.

**Comment by ThiashaV** [comment]
@danangmassandy protected areas field missing from pop-up window. this window also shows up when a parcel is clicked on, not hovered over (I am just noting the difference even though it's perfectly fine)
![image](https://github.com/kartoza/sawps/assets/98025261/4e4e58c3-e0eb-4b7d-82e5-5bae7ec0155a)
