### ISSUE TITLE
Add a popup window with a description when clicking on the map element

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#583]
For example, a pop-up info window showing the ecosystem type if a polygon is clicked

**Comment by ThiashaV** [comment]
A description of each map element shows up as a popup window when the user hovers over the element. 
![image](https://github.com/kartoza/sawps/assets/98025261/12ec5727-251a-49ee-aefe-e19fa9cbca1d)

**Comment by ThiashaV** [comment]
same as [ issue 564](https://github.com/kartoza/sawps/issues/564)

Instructed to close this issue and work from 564 by @amyburness
