### ISSUE TITLE
Create the species data upload forms

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#584]
![Image](https://github.com/kartoza/sawps/assets/90245715/a37fb12d-6493-46a1-bdfd-1ff9355f5530)

This will be done only once the wireframe is updated as per the new database.

For more details on the existing data template that will be provided to the users, go to Projects>IDS>SANBI>DATA> 2023 Integrated Data template V3 excel file

**Comment by ThiashaV** [comment]
species data upload form contains species detail, activity detail and review and submit section. It allows you to save as a draft, and when you return later, all of your information is still saved. and it has a submission option for once you are happy with the way you filled out the form 
![image](https://github.com/kartoza/sawps/assets/98025261/6aa90ca1-9348-4dc4-9040-ebe866d7f8ef)
