### ISSUE TITLE
Build the notifications and reminders pages for the user

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#590]
please build the user reminders and notifications pages. they need to ba able to set up reminders and view all notifications from the system. 

Reminders: 

![image](https://github.com/kartoza/sawps/assets/77841514/071be693-5990-495a-8ff8-39919531c553)
![image](https://github.com/kartoza/sawps/assets/77841514/3985c7b1-16f5-42f3-9a3a-f70ee93dfdff)

Notifications pages:

![image](https://github.com/kartoza/sawps/assets/77841514/94d54579-9ba7-42c1-aad2-c6820e99b3c6)
![image](https://github.com/kartoza/sawps/assets/77841514/f80b269f-9537-4e70-ab1c-9ee6d1516f5c)

**Comment by amyburness** [comment]
@DONOTFORGET-BYTE we should use **Django messaging** to build the user reminders and notifications

**Comment by DONOTFORGET-BYTE** [comment]
![addreminder_modal](https://github.com/kartoza/sawps/assets/70011086/4df9a9ee-5a75-40b1-9ba2-7dcb2a2af9ba)
![reminders](https://github.com/kartoza/sawps/assets/70011086/bd13f7c0-eac7-4d86-932f-8b05e3143cc2)

**Comment by DONOTFORGET-BYTE** [comment]
![add_reminder_modal](https://github.com/kartoza/sawps/assets/70011086/432d29ee-2625-4e60-9b22-790a5ea3ae5c)
![notifications](https://github.com/kartoza/sawps/assets/70011086/614ee776-0633-448f-8264-a7fc1e008f1a)
![reminders_page](https://github.com/kartoza/sawps/assets/70011086/d115894c-9b9a-4e3a-be59-a134990687e5)
![delete_modal](https://github.com/kartoza/sawps/assets/70011086/92fa85c9-4b52-4493-a8cb-85e4aeb89eda)
![edit_reminder_modal](https://github.com/kartoza/sawps/assets/70011086/303dd144-fb38-405e-9066-e6ab1c684ac2)
@amyburness
