### ISSUE TITLE
Wireframe: Admin Environment (Admin)

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/sawps#6]
We need a administration environment page to be able to link to:
- User Administration
- Roles and Permissions
- Add Spatial Layers
- Add / Configure Species 
- Data Security
- Specific species Events Content

Should link to the following pages:
- Users 
- Roles and permissions
- Spatial layers
- Species 
- Data Security

**Comment by amyburness** [comment]
Yes Admin environment.
