### ISSUE TITLE
We need to have Review and Submit Tab in data upload flow

### ISSUE THREAD

**Issue by danangmassandy** [kartoza/sawps#612]
This is part of #584.
User should be able to review their form before submitting to the server.

![Image](https://github.com/kartoza/sawps/assets/5819076/302513fc-5a16-4349-9884-62eb92f2288b)

**Comment by ThiashaV** [comment]
![image](https://github.com/kartoza/sawps/assets/98025261/20f09de3-09f5-465a-b11a-fe43f1dccab4)
