### ISSUE TITLE
We need to work on a user organisation request

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#631]
@DONOTFORGET-BYTE 
We need to work on having a user that has registered onto the platform without an organisation be able to request an organisation from the SANBI administration. 

Let's remove this from the profile page @Fanevanjanahary 
![image](https://github.com/kartoza/sawps/assets/77841514/aac6f3f7-9cf1-4b1a-acdc-a525e819e6fa)

@DONOTFORGET-BYTE 
if the user doesn't have and organisation can we have a button in the dropdown under organisation that says request organisation. that if pressed a popup showing the following opens where the user can send a message to the admin or request an organisation. 
![image](https://github.com/kartoza/sawps/assets/77841514/766e6b4f-348c-4342-ae10-5467070f77ca)

Once the button is pressed then the user should get a popup similar to the following that allows them to send a request to the admin for an organisation. 
![image](https://github.com/kartoza/sawps/assets/77841514/24acb03f-b329-46d4-9f15-c69461ac5832)

**Comment by DONOTFORGET-BYTE** [comment]
On organisation name is it a dropdown that fetches the organisations or they just enter a name

**Comment by DONOTFORGET-BYTE** [comment]
Alright so this is also just basically sending an email to the administrator that a user request to join an organisatio?

**Comment by DONOTFORGET-BYTE** [comment]
![modal](https://github.com/kartoza/sawps/assets/70011086/2a321f2b-5702-4e0d-8230-d66fe0c889bd)
![request_form](https://github.com/kartoza/sawps/assets/70011086/5158b015-41a6-4ef3-a63c-f015e718ad55)
![request_org_btn](https://github.com/kartoza/sawps/assets/70011086/1afb3284-a46e-417c-8b3c-09000b076f6c)
@amyburness I have these now I need to verify something on the logic , so the user will enter the organisation they want right , so on the backend it should search for that organisation representative and retrieve their email and send that request notification to their email ?

**Comment by amyburness** [comment]
I tested this it is working great. 
![image](https://github.com/kartoza/sawps/assets/77841514/57398d1f-8a88-4d3e-bb98-cc71a71356e9)
We can discuss in the SAWPS planning session about connecting this to the admins notifications so that they also get a system notification when a user requests an organisation.

**Comment by LunaAsefaw** [comment]
@amyburness is this available to all users or just users without an organisation?
