### ISSUE TITLE
Contribute to user documentation while testing

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#635]
@Jeremy-Prior @tharanathkartoza 
Please make user documentation while testing with screenshots and simple instructions on the documentation site. 

![image](https://github.com/kartoza/sawps/assets/77841514/5e582314-fbdb-4d90-9a90-896975fc8138)

**Comment by Jeremy-Prior** [comment]
@amyburness moving this back to `To Be Estimated` for the moment as the contribution to the user guide has changed.
