### ISSUE TITLE
Dark map background should match site theme

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#637]
![Peek 2023-07-11 09-08](https://github.com/kartoza/sawps/assets/178003/c6c13715-6687-4aad-a36a-6ebfb4680ae0)

Should use #282829

**Comment by Jeremy-Prior** [comment]
@timlinux The SADC countries' fill is different to the background intentionally?

**Comment by Jeremy-Prior** [comment]
![issue637_1](https://github.com/kartoza/sawps/assets/100694811/5ede1147-de13-4d91-bfe0-bef07588d7c3)
