### ISSUE TITLE
10% zoom threshold around parcels

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#638]
![image](https://github.com/kartoza/sawps/assets/178003/25be76e0-1bf6-4caf-b8b5-afb071d98277)

Let's not clip the zoom right onto the bbox of the parcels. Rather get the bbox and expand it by 10% so the parcels dont run right up to the edge of the map. This same approach should be used whenever we are visualising a property.

**Comment by danangmassandy** [comment]
I have updated the preview:

![Image](https://github.com/kartoza/sawps/assets/5819076/92b04a82-98f1-4904-b47c-6f366bc3d50b)
