### ISSUE TITLE
Header bar takes up too much space

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#639]
![image](https://github.com/kartoza/sawps/assets/178003/62c62051-26eb-4b64-b95e-d8e084d57dba)

On the landing pages, we can have a taller bar (1) but on the detail screens we should come up with a more compact version so that the bar does not use so much vertical space. Vertical space is our most precious resource, especially on small displays, so we should optimise this as much as possible.

**Comment by DONOTFORGET-BYTE** [comment]
![2023-07-14_11-38](https://github.com/kartoza/sawps/assets/70011086/beff0a90-a0ef-47db-8965-77d898f2590e)
reduced size

**Comment by amyburness** [comment]
This is looking great. We should implement it on all pages i.e landing, about, contact, help, profile pages etc. 
it looks cleaner and allows more space for the page information.
@DONOTFORGET-BYTE
