### ISSUE TITLE
Incorrect road width

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#640]
![image](https://github.com/kartoza/sawps/assets/178003/abb62248-411c-4b24-8933-c8a23f4294a9)

This apparently minor road (1) is much thicker than what looks like an arterial road (2). Can you check it and see if something is misconfigured?

![Uploading Peek 2023-07-11 09-54.gif…]()

**Comment by Jeremy-Prior** [comment]
(1) is an ecological support area polygon?

![image](https://github.com/kartoza/sawps/assets/100694811/ac795e3e-6401-4a2b-a334-e73b1d76be6e)

**Comment by Jeremy-Prior** [comment]
This did highlight an issue with the light styling that has since been remedied

**Comment by amyburness** [comment]
@Jeremy-Prior Are we going to update the dark mode ecological areas and CBA to match the legend. 
Also on the legend the these are the Bioms not the ET's there are like 300 ET's i think they may be a different field in the same data set. 
1. can we update these?
2. we may need to discuss and with @danangmassandy the best way to sow all 300 effectively as I think a super long legend may not be useful. 
![image](https://github.com/kartoza/sawps/assets/77841514/5e335fb9-db04-49aa-87ab-13bf2c25ba55)

**Comment by Jeremy-Prior** [comment]
1) The dark mode ecological areas and CBA use the same colours as in the legend. The hex code was taken from the styles, the opacity is just lowered on the map as otherwise too much detail is lost..
2) Those are indeed the the biome types, as those are how the layers are styled. The db table likely does not include the 300 different ecosystems as columns that weren't needed for the styling were dropped per instruction.

**Comment by amyburness** [comment]
@Jeremy-Prior I'll chat with Mat I think lets keep the legend as is but rename the layer to biomes. 
However the ecosystem type information is definitely needed for the user perhaps we just show it in the click popup. 
we will need to have another look at it.

**Comment by Jeremy-Prior** [comment]
Styling 300 layers will be a long setback as there will be no quick way to make a json style of 300 layers.

**Comment by amyburness** [comment]
@timlinux what are your thoughts? I know Mat want The ecosystem types on the map to be clickable but perhaps not in the layers with a legend. 300 types may be a stretch, How practical is it to add them?

**Comment by Jeremy-Prior** [comment]
Added the ecosystem types to the db (name_18 column in the ecosystem tables).
