### ISSUE TITLE
profile page: update title doesn't work

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#648]
@DONOTFORGET-BYTE please allow the profile form updates to work. I can't update my title it returns a 505 error. 
![updatemrs](https://github.com/kartoza/sawps/assets/77841514/0490536d-774c-433b-b320-04b0ad8092a6)

**Comment by amyburness** [comment]
This is working great. 
I think when the user does press update button they should get a popup saying "changes saved" or something similar.

**Comment by DONOTFORGET-BYTE** [comment]
> This is working great. I think when the user does press update button they should get a popup saying "changes saved" or something similar.

okay no problem. I'll add that
