### ISSUE TITLE
Reset password functionality

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/sawps#651]
There seem to be no way to reset your forgotten password?
![image](https://github.com/kartoza/sawps/assets/107027990/935aebb5-c4c2-4c3e-bd90-4f80e7b97941)

**Comment by timlinux** [comment]
Also the forgot password confirmation english needs review.

**Comment by DONOTFORGET-BYTE** [comment]
so I can leave this ticket in the progress section ?

**Comment by amyburness** [comment]
@DONOTFORGET-BYTE Yes please put some screenshots of the dialogues for the forgot password here so I can review the English. Leave it in progress.

**Comment by DONOTFORGET-BYTE** [comment]
alright . Also the pr for the forgot password has been approved so you can test it out on the staging site

**Comment by DONOTFORGET-BYTE** [comment]
![Image](https://github.com/kartoza/sawps/assets/70011086/696741eb-eea8-4af9-b28f-2800c2537844)

**Comment by DONOTFORGET-BYTE** [comment]
![Image](https://github.com/kartoza/sawps/assets/70011086/9d633b1f-9471-468a-b25d-72083949a128)
![Image](https://github.com/kartoza/sawps/assets/70011086/b7289069-993e-49d1-aaea-78724ea34587)
![Image](https://github.com/kartoza/sawps/assets/70011086/3eecfcaa-4b5a-4581-b715-5f02d7a395db)

**Comment by DONOTFORGET-BYTE** [comment]
@amy so sorry about that I had forgotten to push the updated login page but I've done so now , so anytime Dimas approves the pr you will see it.
