### ISSUE TITLE
R code uploader

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#656]
We need to make a place on the system where the statistician can input an R code that creates 

1. user interface for adding the R code (A selector to choose a species)
2. run the R code and get outputs
3. make visualizations/charts (should work together with the visualization @ketankartoza is making)

there should be a generic R model for a species that does not have a specific model. 

![image](https://github.com/kartoza/sawps/assets/77841514/c14e1444-f117-44bd-b7e0-40652f5450b7)

**Comment by danangmassandy** [comment]
@dimasciput @timlinux, I'm not familiar with R at the moment, is there a sample code that I can use to test? if not, please point me to reference of the similar code that we're going to use in the system, I can start from there.

**Comment by danangmassandy** [comment]
I have some updates in Draft PR #681. The PR does not include UI yet, but it has functionalities to execute R codes. Below is the diagram on the execution of R codes.

![Rcodes](https://github.com/kartoza/sawps/assets/5819076/48fc90c4-e93d-4204-acc8-9f7974abc443)

During exporting data, only species population data in selected organisation are exported. The data contains selected columns: property, species, year, estimate_population, survey_method, and count_method. These variables are available to be used in the R codes.

This is a preview of the R codes, it will plot column property with estimate_population into a graph.
![2023-07-19_19-23](https://github.com/kartoza/sawps/assets/5819076/1616314f-5edd-4760-845a-dea854b111fd)

The exported graph is below:
![estimate_population](https://github.com/kartoza/sawps/assets/5819076/be791062-30df-4853-b197-115a29a6d50b)

@dimasciput @timlinux let me know your thoughts!
