### ISSUE TITLE
enforce User roles

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#657]
The User roles for the site need to be enforced as per the following User Role Organogram. 
![image](https://github.com/kartoza/sawps/assets/77841514/d740e916-ca78-49fa-a926-3a7f728c20d5)

**Comment by danangmassandy** [comment]
@amyburness for decision maker role, the description says the user can upload data for the region (national/provincial level, isn't it). Is the upload for the region new feature? because what we have right now is upload for each property.

**Comment by amyburness** [comment]
@danangmassandy @tinashechiraya 
I am keen to apply this functionality this week. let's schedule a quick meeting for tomorrow morning the discuss.

**Comment by danangmassandy** [comment]
@amyburness could you share the excel for role access matrix?

**Comment by amyburness** [comment]
https://docs.google.com/spreadsheets/d/1WMdjvTNTiZ2yPVzcX6BP5SNCGWGZ3oxxvuoSmhisYN4/edit#gid=0
 
 No there is no upload for a region. They can only upload data if they are also part od an organization as a data contributor.

**Comment by amyburness** [comment]
The spread sheet is the most up to date and has been approved by Mat please follow that. 
The organogram needs some updating.
