### ISSUE TITLE
change "biodiversity areas" to "Critical Biodiversity Areas" on map

### ISSUE THREAD

**Issue by Mattyc84** [kartoza/sawps#671]

**Comment by amyburness** [comment]
@danangmassandy can we change the layer name here to Critical Biodiversity Areas
![image](https://github.com/kartoza/sawps/assets/77841514/c5ca5760-a3a7-46c5-a26b-b5b0a66408b9)

**Comment by amyburness** [comment]
parent ticket #600

**Comment by amyburness** [comment]
The case of the label in not consistent Please change it to Critical biodiversity areas 
@danangmassandy
