### ISSUE TITLE
Species dropdown menu on data upload mixes up species, kingdoms and classes

### ISSUE THREAD

**Issue by Mattyc84** [kartoza/sawps#675]
The taxonomic backbone has clearly been copied incorrectly. You have Animalia (Kingdom), Carnivora (class), Pantherinae (family) and then species names all in the dropdown. Please refer to my email on this where I have tried to address this

**Comment by amyburness** [comment]
@danangmassandy This is similar to the issue to the one I showed Ketan where the dropdown needs to only show the species level taxon entries for the dropdown list. 

![image](https://github.com/kartoza/sawps/assets/77841514/b0ac6889-96e5-4f61-93e5-2fcc4c3f74df)

**Comment by amyburness** [comment]
Fixed
