### ISSUE TITLE
Allow multiple offtake events to be recorded on the online form

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#693]
:exclamation: Issue
Currently the online form only allows one offtake event to be recorded per year, per species. However, more than one type of offtake events can take place in the same year for a specific species.

:bulb: Solution
Allow users to add multiple events such that after one event is recorded, it is added to the row and displayed on the screen for the user to see then the fields can then be populated again but it must now be for a different offtake event.

**Comment by amyburness** [comment]
@danangmassandy see the screenshot below for the basics of the update required.
![image](https://github.com/kartoza/sawps/assets/77841514/0b462756-08a7-4cde-8360-1dd0b0bdcbde)

Let me know if you need more info.

**Comment by danangmassandy** [comment]
Preview:

![Image](https://github.com/kartoza/sawps/assets/5819076/bf1fa548-b799-4b20-a6a5-bae5ab73563d)

**Comment by amyburness** [comment]
done
