### ISSUE TITLE
Delete and Edit button for reminder form

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#695]
❗ Issue
The current reminder form does not allow user to delete or edit input.

💡 Solution
Have an edit and delete icon on recorded reminders

**Comment by DONOTFORGET-BYTE** [comment]
@LunaAsefaw Just to get more context you mean on each reminder should be a pencil icon and a delete icon so that would for example be on the last column of the table ?
![for_luna](https://github.com/kartoza/sawps/assets/70011086/bf985a43-5e54-49d9-b95a-f51334ec3f3f)

**Comment by LunaAsefaw** [comment]
Yes, that's what I understood from this. @amyburness ?

**Comment by amyburness** [comment]
@DONOTFORGET-BYTE 

Can you update the colours for the status to these? 
purple
green
orange

Yes Please do the following 
1. make when the user clicks on the reminder row it opens for editing
2. put a delete button in the last column similar to the one in organisations

**Comment by DONOTFORGET-BYTE** [comment]
@amyburness Alright no problem

**Comment by LunaAsefaw** [comment]
@amyburness this should have an edit icon too right? The delete function works

![Image](https://github.com/kartoza/sawps/assets/90245715/98ba7a65-e2c7-4dcb-a36f-b798ed074ac4)
