### ISSUE TITLE
Use Case 1/3: Add new user account/Assign roles & permissions to user accounts

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/sawps#7]
We need a users page to be able to:
- View and configure user permissions
- Admin add a user
- Link data provider properties

Should link to:
- Add user form

The administrator should be able to add users and information. The system should also collect data related to users and be displayed in a logical manner. The complete list of information collected from the users are still TBC but include validated personal information (email and cellphone) spatial information (property location and boundaries and species information (species of animals kept). Before a user can access the system the user MUST also agree that information can be collected with in their limited right and stored in a POPIA compliant manner.

**Comment by amyburness** [comment]
Yes to admin features #657
