### ISSUE TITLE
Update text on about Page. 

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#711]
Please update the text on the About page to: "A coordinated wildlife trade monitoring system with centralised/shared information about priority species such as rhino, lion, leopard, cheetah, elephant and more."

![image](https://github.com/kartoza/sawps/assets/77841514/40b0fd60-18b7-4506-8a21-7eeeeca557da)

**Comment by LunaAsefaw** [comment]
checked. :white_check_mark: 
![image](https://github.com/kartoza/sawps/assets/90245715/ee0aa65a-24f0-460b-931c-470a83e4461d)

**Comment by amyburness** [comment]
@tinashechiraya can we change the word coordinated to cenralised?

**Comment by amyburness** [comment]
See ticket #967
