### ISSUE TITLE
Url should match user location in view

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#720]
![image](https://github.com/kartoza/sawps/assets/178003/ce57b152-50d8-484b-b5eb-286cf459f818)

**Comment by LunaAsefaw** [comment]
@tinashechiraya currently it referes to each one by tab number (eg tab 1)

![Image](https://github.com/kartoza/sawps/assets/90245715/ec54d1ea-c429-4883-bd5d-bddb311456bd)

Would it be possible to say data instead of tab 1 and metrics instead of tab 2 etc
