### ISSUE TITLE
Fields per offtake event

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#731]
If offtake event = 'Translocation intake': Translocation source and permit number are available fields.

If offtake event = 'Translocation offtake': Translocation destination and permit number are available fields.

If offtake event = 'Planned hunt/cull': Translocation destination is not included but permit number is.

If offtake event = 'Planned euthanasia/DCA': Translocation destination is not included but permit number is.

If offtake event = 'Unplanned/illegal hunting': Translocation destination and permit number are not included.

**Comment by danangmassandy** [comment]
@LunaAsefaw I don't see field for 'Translocation source' in the data model:

![Image](https://github.com/kartoza/sawps/assets/5819076/ce6e568d-a310-45a9-83be-33b0e3a15740)

**Comment by danangmassandy** [comment]
This has been implemented via #780

**Comment by LunaAsefaw** [comment]
translocation is missing translocation destination and permit
![Image](https://github.com/kartoza/sawps/assets/90245715/9dbb68ea-5699-4396-88bb-2050435cc9d6)
