### ISSUE TITLE
we need an information pannel that opens when a property is clicket on the map

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#745]
@tinashechiraya 

When the property is clicked on then the information pannel should open on the right side of the screen. 

![image](https://github.com/kartoza/sawps/assets/77841514/a1751b6e-aa4c-472d-bf9f-8395d45583af)

Please talk to @danangmassandy who originally started on this feature (the information has been updated.
Pleas also talk to @ketankartoza and use the charts he has made in this panel.

**Comment by LunaAsefaw** [comment]
Tested and approved. Moving to the next column

![Image](https://github.com/kartoza/sawps/assets/90245715/9218203d-8251-4f95-b5f8-2de65885945c)

**Comment by amyburness** [comment]
This I not wrking in current version of the site @tinashechiraya
