### ISSUE TITLE
We need to update the spacing on the dashboard graphs.

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#746]
@ketankartoza there is a lot of space waisted in the areas of the graph. can we make them all more efficient, especially in the use of vertical space? 
Please reduce the height of the graph areas so that the layout is more similar to the red boxes in the screenshot. 

![image](https://github.com/kartoza/sawps/assets/77841514/4a01242b-cbbc-40f7-b0aa-2af435c1a92f)

**Comment by amyburness** [comment]
![Uploading image.png…]()

**Comment by LunaAsefaw** [comment]
All the graphs need to have these dimensions:
height: 240 px
width: 750 px @ketankartoza

**Comment by amyburness** [comment]
@ketankartoza see the update layout here. 
![graphs 2](https://github.com/kartoza/sawps/assets/77841514/7de04088-d27d-4061-bfc2-b640daa180f9)
