### ISSUE TITLE
Separate density and total count to two different charts

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#762]
Currently the total population count and the population density are displayed on the same chart but they have significantly different scales (eg count could be 2000 while density is 14) so to avoid this, separate these two graphs.

![Image](https://github.com/kartoza/sawps/assets/90245715/48da19ce-9573-4ad4-aedc-cc4e97003790)

@amyburness said she will update the figma board and @ketankartoza is in charge of the implementation on the staging site

**Comment by amyburness** [comment]
@ketankartoza remove the total count bar chart and just make it density. 
![image](https://github.com/kartoza/sawps/assets/77841514/6a410ac2-face-4f82-aef2-480271859b81)
