### ISSUE TITLE
we need a new chart: Total are available to species (ha)

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#765]
@ketankartoza can you add a new visualization Total are available to species (ha)
![image](https://github.com/kartoza/sawps/assets/77841514/e65dc761-1aba-4b7e-b5fe-97053b946a63)

**Comment by LunaAsefaw** [comment]
Able to see this. Passing it to the next column
![Image](https://github.com/kartoza/sawps/assets/90245715/6ada10b4-eca4-4ca7-9ec6-9c3356b827fe)

**Comment by LunaAsefaw** [comment]
No longer used
