### ISSUE TITLE
we need a new chart: Total area per property type

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#766]
@ketankartoza  please add a new chart for Total area per property type
![image](https://github.com/kartoza/sawps/assets/77841514/045d0812-75f8-43d6-bb2a-0b19b8efb25b)

**Comment by LunaAsefaw** [comment]
This does not show in the staging site
![Image](https://github.com/kartoza/sawps/assets/90245715/4d0c5027-3970-4e12-a1aa-1b411960f2a6)

**Comment by LunaAsefaw** [comment]
No longer implemented this way
