### ISSUE TITLE
Pie chart indicating the total population count per species per property type

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#771]
This is the general idea (colours not specified)

![Image](https://user-images.githubusercontent.com/90245715/259644976-d151b56a-11db-45c2-9bd9-b6b7b5c3c17a.png)

**Comment by amyburness** [comment]
@LunaAsefaw I think this is only really useful at a national or regional level. but lets discuss in the meeting today. 
also lets make the title "Totoal population count for elephant per property type" and then "Totoal population count for lion per property type" so there is one graph for each species depending on the filters that the user chooses.

**Comment by LunaAsefaw** [comment]
No longer implemented this way
