### ISSUE TITLE
Pie chart indicating the total population count per species per province

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#772]
General idea (colours not specified)

![Image](https://user-images.githubusercontent.com/90245715/259645531-78cc7a4a-255c-448e-94b8-ecaa40c9f57f.png)

**Comment by amyburness** [comment]
@LunaAsefaw again this is probably only useful for the national and regional users. 
I think we need to make a mock dashboard for that type of user that Ketan can work from so there is no confusion between the normal user and the decision maker.
