### ISSUE TITLE
We need to implement the automated reporting for a national level

### ISSUE THREAD

**Issue by amyburness** [kartoza/sawps#777]
@tinashechiraya 

We need to make a range of automated reports for the system at different  levels 
1. For all users we need a PDF with the full map on it highlighting all of south Africa with some summary statistics followed by the population trend graphs for all the species on the landing page. 
2. For regional users we need a PDF with the region of intered highlighted on it (e.g. limpopo)  with some summary statistics followed by the population trend graphs for all the species on the landing page.

Talk to @Jeremy-Prior  about getting the map tiles made for these.

See the sample report here 
![Report_national](https://github.com/kartoza/sawps/assets/77841514/6264e1df-8cf8-4fc5-9039-1c34655cad3d)

**Comment by LunaAsefaw** [comment]
@tinashechiraya more pages have been added for the report. 


![Image](https://github.com/kartoza/sawps/assets/90245715/6c9ff278-9dd1-40f0-9752-2939c4f33cbc)


For the population pyramid, please make them the same colours as the other graphs so lion is green, leopard is orange etc. I couldn't edit it. You can make the male and female just different versions of the colour
![Image](https://github.com/kartoza/sawps/assets/90245715/d490dc3d-1f6c-44fe-b3ff-e3655477cb61)



![Image](https://github.com/kartoza/sawps/assets/90245715/923a5ef9-cf60-4a97-8797-c00d5212a237)



![Image](https://github.com/kartoza/sawps/assets/90245715/18aee22a-00e9-4f03-9f95-84bd75005bc3)
