### ISSUE TITLE
Update Data tab for regional and national data consumers

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#789]
The Data tab should display the following for national users

![Image](https://user-images.githubusercontent.com/90245715/260425664-4731a38d-8882-4ddb-a244-8de3b0f44b2f.png)

![Image](https://user-images.githubusercontent.com/90245715/260426246-8f99257b-5764-4830-8410-9894b3cfb665.png)

![Image](https://user-images.githubusercontent.com/90245715/260426298-8b0eb6c9-73bf-4a10-8789-4e18f545c81a.png)

For regional users, they will have the same tables but the table shown in red 'provincial information' is excluded because regional users only see data for their region and not for the other provinces but regarding the other tables, they remain as is but the data will be filtered to just show the summary data for their specific region

**Comment by LunaAsefaw** [comment]
cc @amyburness

**Comment by zamuzakki** [comment]
Currently, user National Data Consumer still see detailed report because they are also organisation member/manager.
@LunaAsefaw will bring this issue to her meeting, and will keep me posted.

**Comment by LunaAsefaw** [comment]
@zamuzakki the selected group is data consumer but my API still says organisational member (which makes sense since I am technically part of an organisation). As we discussed the last time, if the user needs to have actual organisational member roles, they will have a different account. However, if they are regional data consumers but the organisational title comes along with it by default since they belong to an organisation, then make it such that if the group is organisational member and data consumer then it is treated as data consumer

![Image](https://github.com/kartoza/sawps/assets/90245715/7d088657-dfe3-4a92-8331-dbfa8add1c51)


![Image](https://github.com/kartoza/sawps/assets/90245715/87639333-4782-4f49-8b67-2c91888c2a97)


Because currently this selection of user role treats me like a data consumer on the map since I cannot see properties but as a organisational member when I am on the report tab
