### ISSUE TITLE
bug with metrics

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#796]
![Image](https://user-images.githubusercontent.com/90245715/260931374-f6be53de-8a83-4b7b-9ba9-05398ea8ce63.png)

https://github.com/kartoza/sawps/assets/90245715/82215c4e-231e-4db2-a53f-099fe9f9ce2f

**Comment by LunaAsefaw** [comment]
cc @amyburness

**Comment by danangmassandy** [comment]
Preview:
![map fix](https://github.com/kartoza/sawps/assets/5819076/63a61c85-6c0c-4e0f-b71d-d09074cbb81c)
