### ISSUE TITLE
Unable to view organisation

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#805]
![Image](https://user-images.githubusercontent.com/90245715/261276604-1eab48d4-5290-4af8-b3a8-6425785183e4.png)

**Comment by LunaAsefaw** [comment]
cc @amyburness

**Comment by LunaAsefaw** [comment]
Other comments relating to organisation issues:

![Image](https://github.com/kartoza/sawps/assets/90245715/02354b83-d491-4045-83d1-72718b53ff5b)


![Image](https://github.com/kartoza/sawps/assets/90245715/7419e443-ee0d-42fe-bc5a-f2e5811ad2b1)

**Comment by tinashechiraya** [comment]
@LunaAsefaw should the current member of the organisation be able to see themselves in the organisation members?

**Comment by LunaAsefaw** [comment]
One of the users reported: 'My organisation was there but when I changed from Mr to Dr, it disappeared'. Please don't forget to test this as a normal user or send me details to to login as a normal user @amyburness
