### ISSUE TITLE
See property on a higher zoom level

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#812]
When the user zooms out, they should still be able to see their organisation properties

**Comment by danangmassandy** [comment]
@LunaAsefaw the properties layer is displayed in the same level with parcel layers as of now. I will try to adjust the mininum zoom level to see the properties layer. Any recommendation from you @Jeremy-Prior?

**Comment by Jeremy-Prior** [comment]
Depends on what is meant by the original issue. @LunaAsefaw can your provide more than a single sentence of explanation?

**Comment by LunaAsefaw** [comment]
Add map markers on lower zoom levels showing what properties are where and as the user zooms in, they can see the property better (see image below). Additionally, they can filter by the property to navigate to the specific property and we will implement a search bar to search on a lower level #806 
Allowing property data to be viewed at a low zoom level will slow down the site tremendously 

![image](https://github.com/kartoza/sawps/assets/90245715/9309fbd6-6e56-447e-a96c-500fb50f792c)

**Comment by danangmassandy** [comment]
Based on the discussion, we will show properties as points on higher zoom level.

- [ ] Display properties as points without species filter
- [ ] Display propertie as points with choropleth layer when species filter is applied

**Comment by amyburness** [comment]
@danangmassandy yes at higher zoom levels the  properties should be visualized as points (maybe even with a label with the property name)
Then with a species selected, the points should be coloured with the choropleth colors based on the count for that species on the property.

**Comment by LunaAsefaw** [comment]
@danangmassandy would it be possible to still show this property? I cannot see the property until I zoom in, which has led to users thinking the property is not recorded

https://github.com/kartoza/sawps/assets/90245715/e94cb4b8-3d1e-4224-8c14-38023a913bbc

**Comment by danangmassandy** [comment]
let me check on that @LunaAsefaw, it seems the dot points it's not showing when there is no data.
