### ISSUE TITLE
allow user to edit submitted records

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#815]
I wanted to change the information I put here but could not do that without changing it from the django admin site. Is there another way to edit uploaded info? I tried to edit by selecting the property and clicking on the online form but this allows me to create new records, not edit my existing record so I tried to edit on the data tab but was not able to either. How does a user update submitted records? If the current method is through the Django site then maybe we could allow an edit function here. what do you think @amyburness 

![Image](https://user-images.githubusercontent.com/90245715/261440993-e7108510-5dc4-4cd7-8775-bf113e0cc3db.png)

**Comment by danangmassandy** [comment]
There is ticket #625 to view all the submitted data. We can add edit action to this list and it will bring the user to the same online form with existing data.

**Comment by danangmassandy** [comment]
@LunaAsefaw @amyburness from discussion with Tim, I will implement below:

- Excel Data Upload: add summary of overwritten data
- Online form : Add Edit icon to data table + enable form to update existing data

**Comment by danangmassandy** [comment]
This is the message when upload data overwrites existing data.

![Image](https://github.com/kartoza/sawps/assets/5819076/f69e246b-3a34-4286-ac70-73ba86b6e5c5)
