### ISSUE TITLE
User menu cleanups

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#828]
![image](https://github.com/kartoza/sawps/assets/178003/a2fae804-2a0d-40f9-a002-dcee681c542a)

**Comment by timlinux** [comment]
I think the new implementation still isnt great

Let's move the organisation changing to the profile page rather

![image](https://github.com/kartoza/sawps/assets/178003/0cd20eba-7446-4335-b319-de2627c2c25a)


When clicking that link show a list of all the orgs the user belongs to.

![image](https://github.com/kartoza/sawps/assets/178003/c63265dd-82c0-4fd4-b088-569015470b62)

Then add an option in the list to let the user mark which is active. This should be stored in the db, not in their session as currently implemented.



Then when the user clicks an org in the list, they get the org profile page with items there disabled / enabled as allowed by their role
![image](https://github.com/kartoza/sawps/assets/178003/cb8b83c4-0c21-4525-995f-12988e249825)

**Comment by tinashechiraya** [comment]
@timlinux , @dimasciput The current implementation of storing the organisation id in the session is being made use of on different views and their tests, the organisation members view, the reminders and notifications , so changing the implementation to storing the active organisation in the db and modifying the existing views and tests will require more time and a separate ticket to be made for that ,shall I go ahead and do so?
