### ISSUE TITLE
Site name and favicon

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#829]
![image](https://github.com/kartoza/sawps/assets/178003/c04c39ac-9577-4a65-9327-28205f7ad86f)

**Comment by LunaAsefaw** [comment]
@ketankartoza Instead of Kartoza, it should say 'SAWPS' and it should say that always because upon logging it, it says 'Login' but it should just say SAWPS instead

**Comment by dimasciput** [comment]
This is done
