### ISSUE TITLE
default map to use light theme

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#830]
I think we should default to the light theme for the map. For the dark theme to integrate well, the whole site should have a dark theme and we should move the theme switcher up to the user menu. For now, I think just switching to the light theme by default will be good.

![image](https://github.com/kartoza/sawps/assets/178003/a7a070f0-3cf8-4b8c-aaf7-238e36574b73)

**Comment by danangmassandy** [comment]
this has been implemented via #1305
