### ISSUE TITLE
Rename map to explore

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#831]
![image](https://github.com/kartoza/sawps/assets/178003/ab293f80-1ec6-45c4-aeb8-1c7e59532371)

Map is misleading - when you click on it you can do other stuff like viewing charts etc.

**Comment by LunaAsefaw** [comment]
@tinashechiraya 
![Image](https://github.com/kartoza/sawps/assets/90245715/022ceb66-7c8b-4ff5-a685-695fa410b411)
