### ISSUE TITLE
Tidy button names for downloads

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#834]
![image](https://github.com/kartoza/sawps/assets/178003/394d087d-289d-47e1-a64e-56852f5723b6)

These buttons essentially download the same thing, the only difference is the heading format and the file format.

![image](https://github.com/kartoza/sawps/assets/178003/3e908c60-a532-4f3e-80fa-58cadb9bcf2f)

**Comment by LunaAsefaw** [comment]
![Image](https://github.com/kartoza/sawps/assets/90245715/f80965e7-9633-4a13-a9a0-318c52bd3fbf)



![Image](https://github.com/kartoza/sawps/assets/90245715/9a688d26-7dd0-4c26-8bf2-f595669a759a)

**Comment by LunaAsefaw** [comment]
New ticket for location of popper #1455
