### ISSUE TITLE
Chart grid layout is dodgy

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#836]
You should not need to scroll in the chart view

![image](https://github.com/kartoza/sawps/assets/178003/b08ef61b-0442-44e9-8d9c-f91428c5da73)

Lets move these blocks to the next row and fit 4 blocks per row

![image](https://github.com/kartoza/sawps/assets/178003/99e444c5-68f0-4d22-913a-7c9fa549cd75)

Also we should have the species name show in the activity charts

![image](https://github.com/kartoza/sawps/assets/178003/4226b844-c6e4-4fc9-a7db-056ee714eebd)

**Comment by timlinux** [comment]
Also why is Activity capilised? It is inconsistent with all other chart titles 

![image](https://github.com/kartoza/sawps/assets/178003/f71f966e-0049-41c7-83cc-224395d812ef)

**Comment by timlinux** [comment]
Also why do some species render Activity charts twice?

![image](https://github.com/kartoza/sawps/assets/178003/75999214-e35e-406c-83db-0c33c4a7ce13)

**Comment by ketankartoza** [comment]
> You should not need to scroll in the chart view
> 
> ![image](https://user-images.githubusercontent.com/178003/261995368-b08ef61b-0442-44e9-8d9c-f91428c5da73.png)
> 
@timlinux The horizontal scroll has already been removed. 
> Lets move these blocks to the next row and fit 4 blocks per row
> ![image](https://user-images.githubusercontent.com/178003/261995579-99e444c5-68f0-4d22-913a-7c9fa549cd75.png)
> 
 @timlinux In the upcoming PRs, we will implement a set of graphs for each species which will resolve the issue.
> Also we should have the species name show in the activity charts
> 
> ![image](https://user-images.githubusercontent.com/178003/261996007-4226b844-c6e4-4fc9-a7db-056ee714eebd.png)

**Comment by LunaAsefaw** [comment]
@ketankartoza where/how are these values obtained from? @danangmassandy I recorded some activity details but when I check the data tab, there is no record for any activity whereas those values exist in the django side

![Image](https://github.com/kartoza/sawps/assets/90245715/bd8ab021-fff2-4da5-a7fb-16d8b7d11996)


![Image](https://github.com/kartoza/sawps/assets/90245715/96804c98-6ce9-452b-8c75-6172cd8c6fa2)
