### ISSUE TITLE
Why do we have blank taxa?

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#837]
![image](https://github.com/kartoza/sawps/assets/178003/cea30dc5-3d7e-4a18-8e2e-7b72005df3e8)

**Comment by LunaAsefaw** [comment]
@danangmassandy the data is being pulled from the common names column right then only displaying unique values?  So the taxon rank references (eg Animalia) might be returning null here. Please have a look and exclude them from  
![image](https://github.com/kartoza/sawps/assets/90245715/9ef50600-1102-4ac0-8d10-280f5a77cea7)

**Comment by LunaAsefaw** [comment]
Then maybe we can also list the filter alphabetically
