### ISSUE TITLE
Make a beautiful error page

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#839]
We should avoid errors, but when they do happen the experience should be beautiful. 

![image](https://github.com/kartoza/sawps/assets/178003/4ed7ff52-f938-47ce-b00d-18cb5f4cbdb5)

See here for some inspiration https://freefrontend.com/500-error-page-html-templates/

**Comment by timlinux** [comment]
Also for 404 (page not found) we should have a beautiful page....

**Comment by LunaAsefaw** [comment]
@ketankartoza @danangmassandy @tinashechiraya a few of the pages you're working on showed some error message so I am tagging you on this (even though they have been fixed)
