### ISSUE TITLE
Chrome shows wrong CSS for buttons

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#843]
In chrome on Amy's PC

![image](https://github.com/kartoza/sawps/assets/178003/25fc57bf-041b-4c3c-bf28-19681a66175a)

In FFox on Tim's PC

![image](https://github.com/kartoza/sawps/assets/178003/16fae7cf-341f-4908-ba2b-8aff3790e485)

And then on FFox when I start digitising

![image](https://github.com/kartoza/sawps/assets/178003/5fa217ba-3244-41e3-af99-48cecdb5cdfb)

**Comment by LunaAsefaw** [comment]
@Fanevanjanahary @danangmassandy @ketankartoza @tinashechiraya This is the convention for buttons throughout the website regardless of the search engine:
![image](https://github.com/kartoza/sawps/assets/90245715/0e3aceba-50a5-4f60-a6a7-489fbcf2a862)

**Comment by LunaAsefaw** [comment]
In the case of Upload, it does not look good with black and if we use the lighter shade of grey (used for elephants), it will not look good with the white so maybe let's make the upload button another SANBI colour, maybe red?
