### ISSUE TITLE
Changes to ecosystem type filter

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#849]
The heading of 'Ecosystem Type' on the dropdown filter panel should change to 'Biome' but the pop up called 'Ecosystem type' can stay. However, the data in the pop-up for Ecosystem type should be obtained from the data Jeremy sent (the field is called name18). Therefore, it will no longer be reading 'Savanah' but rather a corresponding value from the field name18

![Image](https://user-images.githubusercontent.com/90245715/262140643-4f117ec3-f9a9-4fe8-a86c-59718789a6fc.png)

**Comment by LunaAsefaw** [comment]
![Image](https://github.com/kartoza/sawps/assets/90245715/e6922893-551e-4cb4-a484-703bdd448fca)
and is the data being pulled from Jeremy's data because what I see on the pop up are still values from the current ecosystem type dropdown @danangmassandy

**Comment by danangmassandy** [comment]
@LunaAsefaw could you please check again? it was deployed but I forgot to reload the fixtures for context layers. now it should be correct.
