### ISSUE TITLE
None of the pages should have a horizontal scroll

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#855]
All the contents displayed on the site should allow vertical scrolls but no horizontal scrolls.

![Image](https://user-images.githubusercontent.com/90245715/262143217-805686d2-f75e-49a4-bb78-ec5bcfa92026.png)

I will upload the new figma design tomorrow for this tab

**Comment by LunaAsefaw** [comment]
@ketankartoza this is the new design for the data tab for data contributed (see figma frame: mapanddataview/tabs/data/datacont) 

![Image](https://github.com/kartoza/sawps/assets/90245715/761435ba-7b4b-4be9-b1d0-17fa80fac414)

**Comment by amyburness** [comment]
table meeting notes: 

Each table must be the same size and the columns inside it can vary in with to fit across the screen. 

for data contributor
 
can we make the rows 30px high and the column with variable to fit the title text

![image](https://github.com/kartoza/sawps/assets/77841514/66b1297c-3468-43a3-b9c5-e6a224685b21)

see 5 rows per table
