### ISSUE TITLE
Data upload: says the upload is successful but no data is uploaded.

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#866]
Issues I encountered with the data upload:
1. When I upload data with intentional errors to test if it provides feedback about records not meeting the standard, it does not let me know. It says it was successful but there is actually no upload.
2. When I upload a clean dataset, it says the upload was successful but the data is not uploaded.
3. The 'upload' button seems to just grey out and can't be used. We have not picked up an exact pattern as to why that happens, it seems random.

**Comment by Fanevanjanahary** [comment]
New implementation:

- [ ] Add a alert message telling if the data is already exist on the database
- [ ] It is possible that the property name in a different row is spelling wrong, do not stop adding the next data
- [ ] After removing file on popup then add new one, the new can't be find
- [ ] Improve the alert message when the data upload is success (tell the number of data uploaded not only the row)
