### ISSUE TITLE
Rethink filter by year approach on the metrics page

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#878]
Currently, the design allows users to filter by year using a range:

![Image](https://user-images.githubusercontent.com/90245715/263369175-3a0f60d0-830b-4b0f-8657-e70f43eef2aa.png)

This works for the time series graph (species population by year because this shows population by year). However, the other graphs only show a specific year at a time or it needs to take the average (which can be misleading if the range is wide). Otherwise, it will just show the sum of all the data (eg if the range is 2009 to 2020, then the elephant density graph would either show the sum or the average).

Proposed system:

![Image](https://user-images.githubusercontent.com/90245715/263369733-91eaf0cc-9f1a-4806-b155-e05c6b9ff339.png)

This applies the year filter on the time series graph but the other graphs that are year-specific have another filter below that allows the user to select a specific year from the years that have been recorded.

**Comment by LunaAsefaw** [comment]
@ketankartoza I have asked @timlinux to review this before it is implemented. I will assign it to you once we get thumbs up or further recommendation

**Comment by timlinux** [comment]
@LunaAsefaw I think it is  better to ask TimK. My recommendation would be to create one graph series per property (i.e. we would need line charts as per my scratch here:

![image](https://github.com/kartoza/sawps/assets/178003/20eee7dd-817f-4280-b18e-fc9eccaef860)


Its going to get cluttered if we have many properties though....

**Comment by LunaAsefaw** [comment]
No longer applicable
