### ISSUE TITLE
Responsive grid on front page

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#887]
If one block cant fit the page, we should wrap them over in groups of 6 first and then 3 and then 2 and then 1 as the screen size degrades so that there is symmetry in the presentation of the group.
![image](https://github.com/kartoza/sawps/assets/178003/40924564-7581-4b8b-9902-b8cccc3d341e)

**Comment by danangmassandy** [comment]
Preview:
![Screenshot_4654](https://github.com/kartoza/sawps/assets/5819076/554486da-3335-4cb6-8171-74967d3f93ba)

![Screenshot_4655](https://github.com/kartoza/sawps/assets/5819076/e6fc4770-d381-45d6-868e-41e5fe3867db)

![Screenshot_4656](https://github.com/kartoza/sawps/assets/5819076/70773e70-3af2-4040-a948-2da3cf9a5689)

![Screenshot_4657](https://github.com/kartoza/sawps/assets/5819076/52069cad-c977-4e68-b83e-ee8ad60d44c9)
