### ISSUE TITLE
Design language for 2fa page

### ISSUE THREAD

**Issue by timlinux** [kartoza/sawps#894]
![image](https://github.com/kartoza/sawps/assets/178003/b2de5225-4ba8-45d0-8043-68c0d10df1f4)

These font sizes etc are inconstent with our design language. Please review figma and get all of the UI aligned. Also please hide the backup codes after they are first issues. User should generate a new set if they need more.

**Comment by Jeremy-Prior** [comment]
The tab name is also tautological.

2FA Authentication = Two Factor Authentication Authentication

![image](https://github.com/kartoza/sawps/assets/100694811/86f97ca1-81ce-4f26-8b25-0866e848c681)

**Comment by tinashechiraya** [comment]
@Jeremy-Prior I have rename it to 2FA only
