### ISSUE TITLE
Remove the layers filter when in the other tabs

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#918]
The layers tab is only necessary if the user is in the 'map' tab. Otherwise, only the filters tab is necessary for the rest

![Image](https://user-images.githubusercontent.com/90245715/264631076-8271fd54-e8e9-4c66-a5b5-cf7e4cd840a3.png)

**Comment by danangmassandy** [comment]
Okay, I can disable the layers tab when the user is in other tabs.
