### ISSUE TITLE
Filter by species on map tab

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#934]
When user filters by species, they should be restricted to selecting just one species instead of multiple species so the side panel stats also focuses on the stats of just one species. When the species is selected, it should zoom in to the species (similar to #933) but the highlighted property should be in the colour of the species (eg green for lions)

![Image](https://user-images.githubusercontent.com/90245715/265499434-747bb651-322d-4840-bfec-423562deee0d.png)

**Comment by danangmassandy** [comment]
TODO:

- [ ] Draw choropleth layer for province based on species count in higher zoom level
- [ ] Draw choropleth layer for properties based on species count

**Comment by danangmassandy** [comment]
These were my notes from our discussion about new map interactions on 20 Oct 2023.

- [ ] Filter by activity and years are applied only when there is selected species
- [ ] Property label should be displayed after province layer
- [ ] Legend is not updating when species/filter is changed
- [ ] Choropleth layer for properties should include property without species population data
- [ ] The choropleth categories must be 5 breaks. We need to handle edge cases: 1) when there is only 1 data, then min=max 2) when the generated breaks is less than 5
