### ISSUE TITLE
Change where the contact us dialogue is

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#966]

**Comment by LunaAsefaw** [comment]
@amyburness please paste description image here

**Comment by amyburness** [comment]
Please move the contact form to the middle of the space. 
if the page was split in half then the form needs to be in the middle of the right half vertically and horizontally. 

![image](https://github.com/kartoza/sawps/assets/77841514/5dc15042-c8bd-4b65-84fd-536b334a6c02)
