### ISSUE TITLE
Changes to the organisation tab in profile

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#968]
![Image](https://user-images.githubusercontent.com/90245715/267337477-afead300-8886-4e9f-965a-83375402eddd.png)

The organisations tab needs to be in table form with four columns:
1.  showing which organisation is active or not
2.  showing organisation name
3. showing a button that allows you to add users and when it is clicked on, you immediately go to the add users dialogue
4. a read more link that when user clicks on it, it takes them to the organisations datasets listed in the table that have another column next to the list of the dataset showing the permissions for the specific datasets. The toggles that were initially found under user profile need to be then removed and added to this table

![Image](https://user-images.githubusercontent.com/90245715/267339700-0ec9e500-2df0-4c09-ab06-732436687e18.png)

@amyburness this is the summary of the ticket in a nutshell right? Anything to add?

**Comment by tinashechiraya** [comment]
@LunaAsefaw ,@Amy 1.so the add user here, do you want it to send an invitation to the user so they join on their own or they should just be automatically added then an email sent to them notifying them that they have been added to an organisation?

**Comment by amyburness** [comment]
the Add user should just take the user through to the form where they can add users to their organisation (only available to managers). I was not immediately clear that you need to click on the table record to go to that form.  

the data use permissions we still nee to discuss a little further.

**Comment by tinashechiraya** [comment]
@amyburness so shall I halt on these switches ? 

[Screencast from 20-09-2023 10:58:20.webm](https://github.com/kartoza/sawps/assets/70011086/73647c32-c801-4965-9e4b-f9b187853f5e)

**Comment by amyburness** [comment]
I am happy for you to have them like that on an Organisational level. 
The issue we discussed with @Mattyc84  is that eventually they may want to add permissions on a data set level but in that case they will be prompted when they upload a dataset and that will overide the overall organisation permissions.

**Comment by tinashechiraya** [comment]
@amyburness Alright thanks
