### ISSUE TITLE
Profile tab layout changes

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#971]
![Image](https://user-images.githubusercontent.com/90245715/267341382-610bbf9e-0ccf-4d54-be59-dcc4f32c81fd.png)

1. There is already a 2FA button, please remove that.
2. Please write 2FA in full
3. Data permissions are no longer on a user level but rather an organisational level so please remove them from this section
4. Move the update button to the bottom right since all the buttons on the site are bottom right.

**Comment by tinashechiraya** [comment]
https://github.com/kartoza/sawps/pull/982
