### ISSUE TITLE
Filter options per tabs and per user role

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#979]
Data scientists, organisational members/managers:
On the map and metrics tab:
1. Property
2. Species
3. Organisation
4. Year
5. Spatial filters

On the data tab:
1. Report type
2.  Property
3. Species
4. Organisation
5. Year
6. Spatial filters

Data consumers
On the map and metrics tab:
1. Species
2. Year
3. Spatial filters

On the data tab:
1. Report type
2. Species
3. Year
4. Spatial filters

**Comment by LunaAsefaw** [comment]
@zamuzakki data consumers limitations need to be implemented

**Comment by zamuzakki** [comment]
@LunaAsefaw Activity filter is missing from all roles.
