### ISSUE TITLE
Graph 1: Population trend graph

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#989]
![Image](https://user-images.githubusercontent.com/90245715/267614172-2a5c5beb-536a-4de8-8c30-76d8c5768a99.png)

**Comment by amyburness** [comment]
Please note the chart matrix for each user role

**Data contributors**
![image](https://github.com/kartoza/sawps/assets/77841514/d6745bce-50e5-4a7d-816c-732af4034b4c)

**Data scientist**

![image](https://github.com/kartoza/sawps/assets/77841514/1565beaa-c67e-4a9c-8e7c-ea4794c97bc8)

**Comment by amyburness** [comment]
@tinashechiraya please implement this graph see the matrix for the user roles and what they can see. 
This graph is based on the R code from Tim K  as a trend but should also have the actual counts per year on it as dots. 
Please take a look at the graph below. 
![image](https://github.com/kartoza/sawps/assets/77841514/6bc36bd9-c5e4-47b3-8996-7ca2b32d2542)

**Comment by LunaAsefaw** [comment]
@zamuzakki  This chart is moved to the trends bar so we have a simple bar graph now to replace this graph: where we see the population count per filtered property by years (count on the x-axis)
![image](https://github.com/kartoza/sawps/assets/90245715/3e66968f-be79-46d9-b051-14404d2121a0)

**Comment by LunaAsefaw** [comment]
@danangmassandy @zamuzakki thie population trend graph will be on the trends tab
