### ISSUE TITLE
Graph 2: Population size category

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#990]
Although the years are determined by the year filter, users can interactively still select which years they would like to see on a specific graph (in case they would like to compare years that are not consecutive, eg 2023 vs 2019). So by default all the years are displayed on the graph based on the year filter but this can then be filtered out some more when users deselect certain years on the legend.

![Image](https://user-images.githubusercontent.com/90245715/267614428-06b9c240-b485-4f36-afde-e0ee7ead7926.png)

**Comment by LunaAsefaw** [comment]
@zamuzakki this is the new chart design:
![image](https://github.com/kartoza/sawps/assets/90245715/8efe550d-2908-4f19-8d57-998532138a55)

**Comment by dimasciput** [comment]
@LunaAsefaw please test in staging

**Comment by LunaAsefaw** [comment]
The data:
![image](https://github.com/kartoza/sawps/assets/90245715/d5f64d82-8500-44e5-a661-0f1ba6b7abf8)

Current filter: all properties, all organisation,1960-2023 for Acinonyx jubatus

The chart:
![image](https://github.com/kartoza/sawps/assets/90245715/eaef7c77-c9f1-4755-a93a-f68930cd5feb)

@dimasciput I think there might be a few issues with the current implementation:
1. It shows areas but the user would like to see the count of properties instead.
2. The 2006 and 2014 records are missing from the chart since they are not part of the legend. Where do these records go?
3.  Aug 23 record has 201 species so it  is expected to be in the last block but for 2023 but in the chart the legend shows 2021 for >102 data, where is aug 23 in this case?
4.  amy 5071 and abc have 20 and 27 species respectively but none of them can be visualised because the lowest value on the chart is 65. How is the interval generated and what happens to these values? 

From my understanding, this is more or less the chart I expected (before we moved away from stacked bar chart) :
![image](https://github.com/kartoza/sawps/assets/90245715/564fed6b-b23b-4501-a805-d3477a9f6a35)

I am worried that stacked bar chart is misleading for this chart, maybe a group chart instead (it has population size category on the y-axis because that depends on the number of years selected so if many years are selected, a horizontal scroll would be needed and we don't want a horizontal scroll on the site) so this is the expected chart now:
![image](https://github.com/kartoza/sawps/assets/90245715/336f223a-0320-4c84-a66f-8ac9409b8c2b)

More context:
![image](https://github.com/kartoza/sawps/assets/90245715/dcd15fb6-3aa2-4cb8-8594-9e3ded7af733)

does this make sense?

**Comment by dimasciput** [comment]
@LunaAsefaw Ah, I see. It's because your design from last week used "area" instead of "count". https://github.com/kartoza/sawps/issues/990#issuecomment-1780824260

I'm also currently using the area available to species instead of the property's total area. I can update this.

Or would you prefer to continue using property count?

**Comment by LunaAsefaw** [comment]
@dimasciput my apologies, that was meant to say count, yes the intention is to count the amount of properties that have a certain number of population
